export type DealCharacter = {
  name: string;
  category:
    | "star-wars"
    | "marvel"
    | "harry-potter"
    | "dc"
    | "fluch-der-karibik"
    | "game-of-thrones";

  kills: number | null;
  height: number | null;
  age: number | null;

  strength: number;
  intelligence: number;
  fame: number;
  attractiveness: number | null;
};

export type DealGameMode =
  | "kills"
  | "height"
  | "age"
  | "strength"
  | "intelligence"
  | "fame"
  | "attractiveness";

export const dealGameModes: {
  id: DealGameMode;
  label: string;
}[] = [
  {
    id: "kills",
    label: "☠️ Wer hat die meisten Kills?",
  },
  {
    id: "height",
    label: "📏 Wer ist am größten?",
  },
  {
    id: "age",
    label: "🎂 Wer ist am ältesten?",
  },
  {
    id: "strength",
    label: "💪 Wer ist am stärksten?",
  },
  {
    id: "intelligence",
    label: "🧠 Wer ist am intelligentesten?",
  },
  {
    id: "fame",
    label: "🌟 Wer ist am bekanntesten?",
  },
  {
    id: "attractiveness",
    label: "❤️ Wer ist am attraktivsten?",
  },
];

export const dealCharacters: DealCharacter[] = [
  // =========================
  // STAR WARS
  // =========================
  {
    name: "Ahsoka Tano",
    category: "star-wars",
    kills: 40,
    height: 179,
    age: 45,
    strength: 91,
    intelligence: 88,
    fame: 92,
    attractiveness: 88,
  },
  {
    name: "Anakin Skywalker",
    category: "star-wars",
    kills: 80,
    height: 188,
    age: 22,
    strength: 97,
    intelligence: 86,
    fame: 98,
    attractiveness: 92,
  },
  {
    name: "Boba Fett",
    category: "star-wars",
    kills: 20,
    height: 183,
    age: 41,
    strength: 83,
    intelligence: 84,
    fame: 94,
    attractiveness: 78,
  },
  {
    name: "C-3PO",
    category: "star-wars",
    kills: 0,
    height: 177,
    age: 67,
    strength: 18,
    intelligence: 87,
    fame: 95,
    attractiveness: null,
  },
  {
    name: "Chewbacca",
    category: "star-wars",
    kills: 30,
    height: 228,
    age: 235,
    strength: 88,
    intelligence: 76,
    fame: 97,
    attractiveness: 62,
  },
  {
    name: "Count Dooku",
    category: "star-wars",
    kills: 20,
    height: 193,
    age: 83,
    strength: 93,
    intelligence: 94,
    fame: 85,
    attractiveness: 76,
  },
  {
    name: "Darth Vader",
    category: "star-wars",
    kills: 100,
    height: 203,
    age: 45,
    strength: 98,
    intelligence: 90,
    fame: 100,
    attractiveness: 81,
  },
  {
    name: "Finn",
    category: "star-wars",
    kills: 15,
    height: 178,
    age: 24,
    strength: 69,
    intelligence: 72,
    fame: 83,
    attractiveness: 87,
  },
  {
    name: "General Grievous",
    category: "star-wars",
    kills: 40,
    height: 216,
    age: null,
    strength: 89,
    intelligence: 83,
    fame: 88,
    attractiveness: 30,
  },
  {
    name: "Grogu",
    category: "star-wars",
    kills: 3,
    height: 34,
    age: 50,
    strength: 74,
    intelligence: 60,
    fame: 97,
    attractiveness: null,
  },
  {
    name: "Han Solo",
    category: "star-wars",
    kills: 35,
    height: 180,
    age: 66,
    strength: 73,
    intelligence: 85,
    fame: 98,
    attractiveness: 91,
  },
  {
    name: "Jabba the Hutt",
    category: "star-wars",
    kills: 0,
    height: 175,
    age: 604,
    strength: 52,
    intelligence: 82,
    fame: 89,
    attractiveness: 12,
  },
  {
    name: "Kylo Ren",
    category: "star-wars",
    kills: 20,
    height: 189,
    age: 30,
    strength: 92,
    intelligence: 80,
    fame: 94,
    attractiveness: 91,
  },
  {
    name: "Lando Calrissian",
    category: "star-wars",
    kills: 10,
    height: 177,
    age: 78,
    strength: 65,
    intelligence: 86,
    fame: 87,
    attractiveness: 92,
  },
  {
    name: "Leia Organa",
    category: "star-wars",
    kills: 15,
    height: 155,
    age: 54,
    strength: 72,
    intelligence: 92,
    fame: 98,
    attractiveness: 91,
  },
  {
    name: "Luke Skywalker",
    category: "star-wars",
    kills: 35,
    height: 172,
    age: 53,
    strength: 97,
    intelligence: 88,
    fame: 100,
    attractiveness: 88,
  },
  {
    name: "Mace Windu",
    category: "star-wars",
    kills: 25,
    height: 192,
    age: 53,
    strength: 96,
    intelligence: 90,
    fame: 89,
    attractiveness: 82,
  },
  {
    name: "Mandalorian",
    category: "star-wars",
    kills: 50,
    height: 180,
    age: 40,
    strength: 85,
    intelligence: 80,
    fame: 92,
    attractiveness: 90,
  },
  {
    name: "Obi-Wan Kenobi",
    category: "star-wars",
    kills: 35,
    height: 181,
    age: 56,
    strength: 94,
    intelligence: 92,
    fame: 98,
    attractiveness: 91,
  },
  {
    name: "Padmé Amidala",
    category: "star-wars",
    kills: 10,
    height: 165,
    age: 27,
    strength: 61,
    intelligence: 91,
    fame: 90,
    attractiveness: 94,
  },
  {
    name: "Palpatine",
    category: "star-wars",
    kills: 15,
    height: 173,
    age: 119,
    strength: 99,
    intelligence: 100,
    fame: 98,
    attractiveness: 35,
  },
  {
    name: "Qui-Gon Jinn",
    category: "star-wars",
    kills: 10,
    height: 193,
    age: 48,
    strength: 91,
    intelligence: 91,
    fame: 88,
    attractiveness: 90,
  },
  {
    name: "R2-D2",
    category: "star-wars",
    kills: 2,
    height: 108,
    age: 67,
    strength: 30,
    intelligence: 93,
    fame: 97,
    attractiveness: null,
  },
  {
    name: "Rey",
    category: "star-wars",
    kills: 10,
    height: 170,
    age: 20,
    strength: 93,
    intelligence: 82,
    fame: 93,
    attractiveness: 91,
  },
  {
    name: "Yoda",
    category: "star-wars",
    kills: 10,
    height: 66,
    age: 900,
    strength: 99,
    intelligence: 98,
    fame: 100,
    attractiveness: 35,
  },

  // =========================
  // MARVEL
  // =========================
  {
    name: "Ant-Man",
    category: "marvel",
    kills: 15,
    height: 183,
    age: 50,
    strength: 78,
    intelligence: 85,
    fame: 88,
    attractiveness: 86,
  },
  {
    name: "Black Panther",
    category: "marvel",
    kills: 30,
    height: 183,
    age: 38,
    strength: 88,
    intelligence: 91,
    fame: 95,
    attractiveness: 94,
  },
  {
    name: "Black Widow",
    category: "marvel",
    kills: 45,
    height: 160,
    age: 35,
    strength: 72,
    intelligence: 90,
    fame: 97,
    attractiveness: 96,
  },
  {
    name: "Captain America",
    category: "marvel",
    kills: 60,
    height: 188,
    age: 106,
    strength: 94,
    intelligence: 88,
    fame: 100,
    attractiveness: 95,
  },
  {
    name: "Captain Marvel",
    category: "marvel",
    kills: 45,
    height: 170,
    age: 60,
    strength: 99,
    intelligence: 84,
    fame: 92,
    attractiveness: 91,
  },
  {
    name: "Daredevil",
    category: "marvel",
    kills: 5,
    height: 178,
    age: 35,
    strength: 79,
    intelligence: 88,
    fame: 87,
    attractiveness: 91,
  },
  {
    name: "Deadpool",
    category: "marvel",
    kills: 100,
    height: 188,
    age: 45,
    strength: 88,
    intelligence: 76,
    fame: 97,
    attractiveness: 83,
  },
  {
    name: "Doctor Strange",
    category: "marvel",
    kills: 25,
    height: 183,
    age: 45,
    strength: 72,
    intelligence: 98,
    fame: 95,
    attractiveness: 90,
  },
  {
    name: "Drax",
    category: "marvel",
    kills: 80,
    height: 193,
    age: 50,
    strength: 95,
    intelligence: 58,
    fame: 89,
    attractiveness: 78,
  },
  {
    name: "Gamora",
    category: "marvel",
    kills: 75,
    height: 170,
    age: 30,
    strength: 90,
    intelligence: 86,
    fame: 91,
    attractiveness: 93,
  },
  {
    name: "Groot",
    category: "marvel",
    kills: 25,
    height: 230,
    age: null,
    strength: 96,
    intelligence: 62,
    fame: 96,
    attractiveness: null,
  },
  {
    name: "Hawkeye",
    category: "marvel",
    kills: 50,
    height: 175,
    age: 52,
    strength: 74,
    intelligence: 87,
    fame: 94,
    attractiveness: 86,
  },
  {
    name: "Hulk",
    category: "marvel",
    kills: 80,
    height: 250,
    age: 55,
    strength: 100,
    intelligence: 96,
    fame: 100,
    attractiveness: 65,
  },
  {
    name: "Iron Man",
    category: "marvel",
    kills: 70,
    height: 185,
    age: 53,
    strength: 70,
    intelligence: 100,
    fame: 100,
    attractiveness: 95,
  },
  {
    name: "Loki",
    category: "marvel",
    kills: 40,
    height: 188,
    age: 1050,
    strength: 92,
    intelligence: 96,
    fame: 100,
    attractiveness: 96,
  },
  {
    name: "Moon Knight",
    category: "marvel",
    kills: 20,
    height: 188,
    age: 40,
    strength: 84,
    intelligence: 81,
    fame: 82,
    attractiveness: 88,
  },
  {
    name: "Rocket",
    category: "marvel",
    kills: 40,
    height: 122,
    age: 15,
    strength: 55,
    intelligence: 94,
    fame: 92,
    attractiveness: null,
  },
  {
    name: "Scarlet Witch",
    category: "marvel",
    kills: 45,
    height: 168,
    age: 30,
    strength: 68,
    intelligence: 88,
    fame: 97,
    attractiveness: 92,
  },
  {
    name: "Spider-Man",
    category: "marvel",
    kills: 30,
    height: 173,
    age: 18,
    strength: 92,
    intelligence: 96,
    fame: 100,
    attractiveness: 91,
  },
  {
    name: "Star-Lord",
    category: "marvel",
    kills: 45,
    height: 188,
    age: 43,
    strength: 76,
    intelligence: 82,
    fame: 93,
    attractiveness: 91,
  },
  {
    name: "Thanos",
    category: "marvel",
    kills: 100,
    height: 250,
    age: 1000,
    strength: 100,
    intelligence: 95,
    fame: 100,
    attractiveness: 67,
  },
  {
    name: "Thor",
    category: "marvel",
    kills: 150,
    height: 198,
    age: 1500,
    strength: 100,
    intelligence: 82,
    fame: 100,
    attractiveness: 98,
  },
  {
    name: "Venom",
    category: "marvel",
    kills: 35,
    height: 230,
    age: null,
    strength: 96,
    intelligence: 72,
    fame: 96,
    attractiveness: 72,
  },
  {
    name: "Vision",
    category: "marvel",
    kills: 20,
    height: 190,
    age: 3,
    strength: 93,
    intelligence: 100,
    fame: 94,
    attractiveness: 83,
  },
  {
    name: "Wolverine",
    category: "marvel",
    kills: 150,
    height: 188,
    age: 200,
    strength: 96,
    intelligence: 79,
    fame: 100,
    attractiveness: 94,
  },

  // =========================
  // HARRY POTTER
  // =========================
  {
    name: "Albus Dumbledore",
    category: "harry-potter",
    kills: 3,
    height: 185,
    age: 115,
    strength: 62,
    intelligence: 100,
    fame: 98,
    attractiveness: 72,
  },
  {
    name: "Arthur Weasley",
    category: "harry-potter",
    kills: 1,
    height: 188,
    age: 48,
    strength: 62,
    intelligence: 84,
    fame: 77,
    attractiveness: 73,
  },
  {
    name: "Bellatrix Lestrange",
    category: "harry-potter",
    kills: 8,
    height: 170,
    age: 47,
    strength: 61,
    intelligence: 84,
    fame: 92,
    attractiveness: 89,
  },
  {
    name: "Cedric Diggory",
    category: "harry-potter",
    kills: 0,
    height: 185,
    age: 17,
    strength: 76,
    intelligence: 82,
    fame: 86,
    attractiveness: null,
  },
  {
    name: "Dobby",
    category: "harry-potter",
    kills: 0,
    height: 106,
    age: null,
    strength: 35,
    intelligence: 79,
    fame: 94,
    attractiveness: null,
  },
  {
    name: "Dolores Umbridge",
    category: "harry-potter",
    kills: 0,
    height: 160,
    age: 50,
    strength: 39,
    intelligence: 82,
    fame: 90,
    attractiveness: 35,
  },
  {
    name: "Draco Malfoy",
    category: "harry-potter",
    kills: 0,
    height: 183,
    age: 17,
    strength: 57,
    intelligence: 83,
    fame: 95,
    attractiveness: null,
  },
  {
    name: "Fred Weasley",
    category: "harry-potter",
    kills: 2,
    height: 180,
    age: 20,
    strength: 70,
    intelligence: 84,
    fame: 88,
    attractiveness: 86,
  },
  {
    name: "George Weasley",
    category: "harry-potter",
    kills: 2,
    height: 180,
    age: 20,
    strength: 70,
    intelligence: 84,
    fame: 87,
    attractiveness: 86,
  },
  {
    name: "Ginny Weasley",
    category: "harry-potter",
    kills: 2,
    height: 168,
    age: 16,
    strength: 67,
    intelligence: 84,
    fame: 91,
    attractiveness: null,
  },
  {
    name: "Harry Potter",
    category: "harry-potter",
    kills: 5,
    height: 175,
    age: 17,
    strength: 72,
    intelligence: 88,
    fame: 100,
    attractiveness: null,
  },
  {
    name: "Hermine Granger",
    category: "harry-potter",
    kills: 2,
    height: 165,
    age: 18,
    strength: 58,
    intelligence: 97,
    fame: 98,
    attractiveness: 92,
  },
  {
    name: "Lord Voldemort",
    category: "harry-potter",
    kills: 25,
    height: 183,
    age: 71,
    strength: 63,
    intelligence: 97,
    fame: 100,
    attractiveness: 20,
  },
  {
    name: "Lucius Malfoy",
    category: "harry-potter",
    kills: 3,
    height: 183,
    age: 44,
    strength: 62,
    intelligence: 86,
    fame: 88,
    attractiveness: 86,
  },
  {
    name: "Luna Lovegood",
    category: "harry-potter",
    kills: 1,
    height: 163,
    age: 17,
    strength: 54,
    intelligence: 89,
    fame: 91,
    attractiveness: null,
  },
  {
    name: "Minerva McGonagall",
    category: "harry-potter",
    kills: 2,
    height: 175,
    age: 70,
    strength: 65,
    intelligence: 95,
    fame: 94,
    attractiveness: 75,
  },
  {
    name: "Molly Weasley",
    category: "harry-potter",
    kills: 2,
    height: 160,
    age: 48,
    strength: 66,
    intelligence: 84,
    fame: 91,
    attractiveness: 76,
  },
  {
    name: "Neville Longbottom",
    category: "harry-potter",
    kills: 4,
    height: 180,
    age: 17,
    strength: 72,
    intelligence: 82,
    fame: 91,
    attractiveness: null,
  },
  {
    name: "Peter Pettigrew",
    category: "harry-potter",
    kills: 13,
    height: 168,
    age: 38,
    strength: 48,
    intelligence: 78,
    fame: 87,
    attractiveness: 38,
  },
  {
    name: "Remus Lupin",
    category: "harry-potter",
    kills: 4,
    height: 188,
    age: 38,
    strength: 72,
    intelligence: 93,
    fame: 91,
    attractiveness: 87,
  },
  {
    name: "Ron Weasley",
    category: "harry-potter",
    kills: 4,
    height: 185,
    age: 18,
    strength: 71,
    intelligence: 82,
    fame: 98,
    attractiveness: 88,
  },
  {
    name: "Rubeus Hagrid",
    category: "harry-potter",
    kills: 2,
    height: 351,
    age: 69,
    strength: 100,
    intelligence: 72,
    fame: 98,
    attractiveness: 65,
  },
  {
    name: "Severus Snape",
    category: "harry-potter",
    kills: 3,
    height: 183,
    age: 38,
    strength: 61,
    intelligence: 97,
    fame: 98,
    attractiveness: 84,
  },
  {
    name: "Sirius Black",
    category: "harry-potter",
    kills: 3,
    height: 180,
    age: 36,
    strength: 73,
    intelligence: 88,
    fame: 95,
    attractiveness: 94,
  },
  {
    name: "Viktor Krum",
    category: "harry-potter",
    kills: 1,
    height: 183,
    age: 21,
    strength: 82,
    intelligence: 78,
    fame: 80,
    attractiveness: 90,
  },

  // =========================
  // DC
  // =========================
  {
    name: "Aquaman",
    category: "dc",
    kills: 25,
    height: 185,
    age: 40,
    strength: 96,
    intelligence: 84,
    fame: 94,
    attractiveness: 95,
  },
  {
    name: "Bane",
    category: "dc",
    kills: 15,
    height: 203,
    age: 40,
    strength: 92,
    intelligence: 90,
    fame: 91,
    attractiveness: 72,
  },
  {
    name: "Batgirl",
    category: "dc",
    kills: 2,
    height: 170,
    age: 25,
    strength: 72,
    intelligence: 92,
    fame: 88,
    attractiveness: 92,
  },
  {
    name: "Batman",
    category: "dc",
    kills: 10,
    height: 188,
    age: 40,
    strength: 86,
    intelligence: 100,
    fame: 100,
    attractiveness: 96,
  },
  {
    name: "Black Canary",
    category: "dc",
    kills: 5,
    height: 170,
    age: 30,
    strength: 75,
    intelligence: 85,
    fame: 86,
    attractiveness: 94,
  },
  {
    name: "Catwoman",
    category: "dc",
    kills: 5,
    height: 170,
    age: 35,
    strength: 71,
    intelligence: 88,
    fame: 96,
    attractiveness: 97,
  },
  {
    name: "Cyborg",
    category: "dc",
    kills: 20,
    height: 198,
    age: 25,
    strength: 94,
    intelligence: 94,
    fame: 91,
    attractiveness: 82,
  },
  {
    name: "Darkseid",
    category: "dc",
    kills: 100,
    height: 267,
    age: null,
    strength: 100,
    intelligence: 97,
    fame: 95,
    attractiveness: 25,
  },
  {
    name: "Deathstroke",
    category: "dc",
    kills: 100,
    height: 193,
    age: 50,
    strength: 89,
    intelligence: 94,
    fame: 89,
    attractiveness: 84,
  },
  {
    name: "Green Arrow",
    category: "dc",
    kills: 15,
    height: 185,
    age: 40,
    strength: 77,
    intelligence: 88,
    fame: 91,
    attractiveness: 93,
  },
  {
    name: "Green Lantern",
    category: "dc",
    kills: 20,
    height: 188,
    age: 35,
    strength: 72,
    intelligence: 87,
    fame: 94,
    attractiveness: 91,
  },
  {
    name: "Harley Quinn",
    category: "dc",
    kills: 30,
    height: 170,
    age: 30,
    strength: 69,
    intelligence: 82,
    fame: 98,
    attractiveness: 96,
  },
  {
    name: "Joker",
    category: "dc",
    kills: 100,
    height: 196,
    age: 40,
    strength: 62,
    intelligence: 96,
    fame: 100,
    attractiveness: 72,
  },
  {
    name: "Lex Luthor",
    category: "dc",
    kills: 15,
    height: 188,
    age: 45,
    strength: 65,
    intelligence: 100,
    fame: 96,
    attractiveness: 83,
  },
  {
    name: "Mr. Freeze",
    category: "dc",
    kills: 10,
    height: 183,
    age: 50,
    strength: 78,
    intelligence: 97,
    fame: 83,
    attractiveness: 70,
  },
  {
    name: "Nightwing",
    category: "dc",
    kills: 5,
    height: 178,
    age: 27,
    strength: 81,
    intelligence: 90,
    fame: 90,
    attractiveness: 97,
  },
  {
    name: "Penguin",
    category: "dc",
    kills: 20,
    height: 157,
    age: 50,
    strength: 43,
    intelligence: 87,
    fame: 92,
    attractiveness: 45,
  },
  {
    name: "Poison Ivy",
    category: "dc",
    kills: 25,
    height: 173,
    age: 30,
    strength: 68,
    intelligence: 93,
    fame: 91,
    attractiveness: 96,
  },
  {
    name: "Robin",
    category: "dc",
    kills: 2,
    height: 165,
    age: 16,
    strength: 68,
    intelligence: 88,
    fame: 96,
    attractiveness: null,
  },
  {
    name: "Shazam",
    category: "dc",
    kills: 5,
    height: 190,
    age: 15,
    strength: 99,
    intelligence: 72,
    fame: 91,
    attractiveness: null,
  },
  {
    name: "Supergirl",
    category: "dc",
    kills: 15,
    height: 165,
    age: 21,
    strength: 99,
    intelligence: 86,
    fame: 95,
    attractiveness: 94,
  },
  {
    name: "Superman",
    category: "dc",
    kills: 20,
    height: 191,
    age: 35,
    strength: 100,
    intelligence: 92,
    fame: 100,
    attractiveness: 98,
  },
  {
    name: "The Flash",
    category: "dc",
    kills: 10,
    height: 183,
    age: 30,
    strength: 76,
    intelligence: 94,
    fame: 97,
    attractiveness: 93,
  },
  {
    name: "The Riddler",
    category: "dc",
    kills: 5,
    height: 185,
    age: 40,
    strength: 50,
    intelligence: 98,
    fame: 91,
    attractiveness: 73,
  },
  {
    name: "Wonder Woman",
    category: "dc",
    kills: 50,
    height: 183,
    age: 800,
    strength: 99,
    intelligence: 92,
    fame: 100,
    attractiveness: 98,
  },

  // =========================
  // FLUCH DER KARIBIK
  // =========================
  {
    name: "Angelica",
    category: "fluch-der-karibik",
    kills: 8,
    height: 168,
    age: 35,
    strength: 71,
    intelligence: 88,
    fame: 83,
    attractiveness: 95,
  },
  {
    name: "Barbossa",
    category: "fluch-der-karibik",
    kills: 35,
    height: 182,
    age: 58,
    strength: 78,
    intelligence: 94,
    fame: 96,
    attractiveness: 72,
  },
  {
    name: "Blackbeard",
    category: "fluch-der-karibik",
    kills: 50,
    height: 188,
    age: 60,
    strength: 88,
    intelligence: 90,
    fame: 88,
    attractiveness: 65,
  },
  {
    name: "Bootstrap Bill",
    category: "fluch-der-karibik",
    kills: 12,
    height: 180,
    age: 50,
    strength: 79,
    intelligence: 75,
    fame: 77,
    attractiveness: 68,
  },
  {
    name: "Captain Teague",
    category: "fluch-der-karibik",
    kills: 30,
    height: 174,
    age: 65,
    strength: 82,
    intelligence: 93,
    fame: 79,
    attractiveness: 72,
  },
  {
    name: "Cotton",
    category: "fluch-der-karibik",
    kills: 8,
    height: 175,
    age: 50,
    strength: 68,
    intelligence: 72,
    fame: 65,
    attractiveness: 60,
  },
  {
    name: "Cutler Beckett",
    category: "fluch-der-karibik",
    kills: 2,
    height: 170,
    age: 40,
    strength: 40,
    intelligence: 96,
    fame: 89,
    attractiveness: 70,
  },
  {
    name: "Davy Jones",
    category: "fluch-der-karibik",
    kills: 60,
    height: 188,
    age: 110,
    strength: 97,
    intelligence: 91,
    fame: 96,
    attractiveness: 35,
  },
  {
    name: "Elizabeth Swann",
    category: "fluch-der-karibik",
    kills: 10,
    height: 170,
    age: 25,
    strength: 69,
    intelligence: 91,
    fame: 97,
    attractiveness: 97,
  },
  {
    name: "Giselle",
    category: "fluch-der-karibik",
    kills: 1,
    height: 168,
    age: 30,
    strength: 50,
    intelligence: 72,
    fame: 62,
    attractiveness: 90,
  },
  {
    name: "Ian Mercer",
    category: "fluch-der-karibik",
    kills: 15,
    height: 180,
    age: 40,
    strength: 75,
    intelligence: 88,
    fame: 63,
    attractiveness: 69,
  },
  {
    name: "Jack Sparrow",
    category: "fluch-der-karibik",
    kills: 25,
    height: 178,
    age: 40,
    strength: 70,
    intelligence: 96,
    fame: 100,
    attractiveness: 94,
  },
  {
    name: "James Norrington",
    category: "fluch-der-karibik",
    kills: 20,
    height: 185,
    age: 35,
    strength: 82,
    intelligence: 90,
    fame: 90,
    attractiveness: 92,
  },
  {
    name: "Joshamee Gibbs",
    category: "fluch-der-karibik",
    kills: 12,
    height: 178,
    age: 50,
    strength: 72,
    intelligence: 84,
    fame: 91,
    attractiveness: 70,
  },
  {
    name: "Lieutenant Theodore Groves",
    category: "fluch-der-karibik",
    kills: 8,
    height: 183,
    age: 35,
    strength: 73,
    intelligence: 82,
    fame: 61,
    attractiveness: 78,
  },
  {
    name: "Marty",
    category: "fluch-der-karibik",
    kills: 5,
    height: 117,
    age: 35,
    strength: 55,
    intelligence: 73,
    fame: 66,
    attractiveness: 67,
  },
  {
    name: "Philip Swift",
    category: "fluch-der-karibik",
    kills: 3,
    height: 183,
    age: 30,
    strength: 72,
    intelligence: 82,
    fame: 68,
    attractiveness: 93,
  },
  {
    name: "Pintel",
    category: "fluch-der-karibik",
    kills: 15,
    height: 178,
    age: 40,
    strength: 74,
    intelligence: 70,
    fame: 81,
    attractiveness: 55,
  },
  {
    name: "Ragetti",
    category: "fluch-der-karibik",
    kills: 12,
    height: 188,
    age: 35,
    strength: 69,
    intelligence: 67,
    fame: 82,
    attractiveness: 58,
  },
  {
    name: "Scrum",
    category: "fluch-der-karibik",
    kills: 8,
    height: 180,
    age: 40,
    strength: 72,
    intelligence: 66,
    fame: 70,
    attractiveness: 62,
  },
  {
    name: "Syrena",
    category: "fluch-der-karibik",
    kills: 3,
    height: 170,
    age: null,
    strength: 82,
    intelligence: 79,
    fame: 75,
    attractiveness: 96,
  },
  {
    name: "Tamara",
    category: "fluch-der-karibik",
    kills: 5,
    height: 168,
    age: null,
    strength: 80,
    intelligence: 75,
    fame: 58,
    attractiveness: 94,
  },
  {
    name: "Tia Dalma",
    category: "fluch-der-karibik",
    kills: 2,
    height: 168,
    age: null,
    strength: 58,
    intelligence: 98,
    fame: 90,
    attractiveness: 87,
  },
  {
    name: "Weatherby Swann",
    category: "fluch-der-karibik",
    kills: 0,
    height: 180,
    age: 55,
    strength: 38,
    intelligence: 86,
    fame: 78,
    attractiveness: 68,
  },
  {
    name: "Will Turner",
    category: "fluch-der-karibik",
    kills: 30,
    height: 180,
    age: 30,
    strength: 84,
    intelligence: 87,
    fame: 98,
    attractiveness: 97,
  },

  // =========================
  // GAME OF THRONES
  // =========================
  {
    name: "Arya Stark",
    category: "game-of-thrones",
    kills: 25,
    height: 155,
    age: 18,
    strength: 66,
    intelligence: 91,
    fame: 98,
    attractiveness: 88,
  },
  {
    name: "Bran Stark",
    category: "game-of-thrones",
    kills: 0,
    height: 180,
    age: 17,
    strength: 35,
    intelligence: 96,
    fame: 91,
    attractiveness: null,
  },
  {
    name: "Brienne von Tarth",
    category: "game-of-thrones",
    kills: 20,
    height: 191,
    age: 32,
    strength: 94,
    intelligence: 83,
    fame: 89,
    attractiveness: 83,
  },
  {
    name: "Catelyn Stark",
    category: "game-of-thrones",
    kills: 1,
    height: 165,
    age: 45,
    strength: 54,
    intelligence: 89,
    fame: 88,
    attractiveness: 85,
  },
  {
    name: "Cersei Lannister",
    category: "game-of-thrones",
    kills: 5,
    height: 166,
    age: 43,
    strength: 52,
    intelligence: 91,
    fame: 97,
    attractiveness: 94,
  },
  {
    name: "Daenerys Targaryen",
    category: "game-of-thrones",
    kills: 120,
    height: 157,
    age: 24,
    strength: 57,
    intelligence: 88,
    fame: 100,
    attractiveness: 97,
  },
  {
    name: "Davos Seaworth",
    category: "game-of-thrones",
    kills: 8,
    height: 185,
    age: 50,
    strength: 69,
    intelligence: 90,
    fame: 87,
    attractiveness: 77,
  },
  {
    name: "Gendry",
    category: "game-of-thrones",
    kills: 10,
    height: 182,
    age: 23,
    strength: 91,
    intelligence: 74,
    fame: 84,
    attractiveness: 93,
  },
  {
    name: "Gregor Clegane",
    category: "game-of-thrones",
    kills: 50,
    height: 206,
    age: 40,
    strength: 100,
    intelligence: 52,
    fame: 92,
    attractiveness: 45,
  },
  {
    name: "Jaime Lannister",
    category: "game-of-thrones",
    kills: 35,
    height: 188,
    age: 43,
    strength: 91,
    intelligence: 88,
    fame: 98,
    attractiveness: 97,
  },
  {
    name: "Jon Snow",
    category: "game-of-thrones",
    kills: 55,
    height: 173,
    age: 24,
    strength: 89,
    intelligence: 84,
    fame: 100,
    attractiveness: 97,
  },
  {
    name: "Jorah Mormont",
    category: "game-of-thrones",
    kills: 40,
    height: 185,
    age: 48,
    strength: 88,
    intelligence: 86,
    fame: 91,
    attractiveness: 87,
  },
  {
    name: "Margaery Tyrell",
    category: "game-of-thrones",
    kills: 0,
    height: 168,
    age: 22,
    strength: 47,
    intelligence: 94,
    fame: 91,
    attractiveness: 97,
  },
  {
    name: "Melisandre",
    category: "game-of-thrones",
    kills: 10,
    height: 168,
    age: 400,
    strength: 54,
    intelligence: 93,
    fame: 92,
    attractiveness: 95,
  },
  {
    name: "Ned Stark",
    category: "game-of-thrones",
    kills: 20,
    height: 179,
    age: 40,
    strength: 84,
    intelligence: 90,
    fame: 97,
    attractiveness: 90,
  },
  {
    name: "Olenna Tyrell",
    category: "game-of-thrones",
    kills: 1,
    height: 174,
    age: 80,
    strength: 35,
    intelligence: 98,
    fame: 89,
    attractiveness: 72,
  },
  {
    name: "Petyr Baelish",
    category: "game-of-thrones",
    kills: 2,
    height: 175,
    age: 40,
    strength: 48,
    intelligence: 99,
    fame: 93,
    attractiveness: 81,
  },
  {
    name: "Robb Stark",
    category: "game-of-thrones",
    kills: 25,
    height: 177,
    age: 20,
    strength: 87,
    intelligence: 87,
    fame: 92,
    attractiveness: 95,
  },
  {
    name: "Samwell Tarly",
    category: "game-of-thrones",
    kills: 5,
    height: 173,
    age: 23,
    strength: 48,
    intelligence: 95,
    fame: 89,
    attractiveness: 77,
  },
  {
    name: "Sandor Clegane",
    category: "game-of-thrones",
    kills: 45,
    height: 198,
    age: 40,
    strength: 96,
    intelligence: 78,
    fame: 96,
    attractiveness: 78,
  },
  {
    name: "Sansa Stark",
    category: "game-of-thrones",
    kills: 1,
    height: 175,
    age: 20,
    strength: 49,
    intelligence: 92,
    fame: 96,
    attractiveness: 97,
  },
  {
    name: "Theon Greyjoy",
    category: "game-of-thrones",
    kills: 20,
    height: 175,
    age: 25,
    strength: 77,
    intelligence: 77,
    fame: 91,
    attractiveness: 86,
  },
  {
    name: "Tormund",
    category: "game-of-thrones",
    kills: 35,
    height: 183,
    age: 40,
    strength: 93,
    intelligence: 71,
    fame: 91,
    attractiveness: 84,
  },
  {
    name: "Tyrion Lannister",
    category: "game-of-thrones",
    kills: 8,
    height: 135,
    age: 40,
    strength: 38,
    intelligence: 100,
    fame: 100,
    attractiveness: 83,
  },
  {
    name: "Varys",
    category: "game-of-thrones",
    kills: 1,
    height: 175,
    age: 50,
    strength: 42,
    intelligence: 99,
    fame: 93,
    attractiveness: 75,
  },
];