export type DealCharacter = {
  name: string;
  category:
  | "star-wars"
  | "marvel"
  | "harry-potter"
  | "dc"
  | "fluch-der-karibik"
  | "game-of-thrones"
  | "herr-der-ringe"
  | "hobbit"
  | "the-boys"
  | "the-walking-dead"
  | "jurassic"
  | "schauspielerinnen"
  | "schauspieler";

  kills: number | null;
  height: number | null;
  age: number | null;

  strength: number;
  intelligence: number;
  fame: number;
  attractiveness: number | null;
};

export type DealGameMode =
  | "kills"
  | "height"
  | "age"
  | "strength"
  | "intelligence"
  | "fame"
  | "attractiveness";

export const dealGameModes: {
  id: DealGameMode;
  label: string;
}[] = [
  {
    id: "kills",
    label: "☠️ Wer hat die meisten Kills?",
  },
  {
    id: "height",
    label: "📏 Wer ist am größten?",
  },
  {
    id: "age",
    label: "🎂 Wer ist am ältesten?",
  },
  {
    id: "strength",
    label: "💪 Wer ist am stärksten?",
  },
  {
    id: "intelligence",
    label: "🧠 Wer ist am intelligentesten?",
  },
  {
    id: "fame",
    label: "🌟 Wer ist am bekanntesten?",
  },
  {
    id: "attractiveness",
    label: "❤️ Wer ist am attraktivsten?",
  },
];

export const dealCharacters: DealCharacter[] = [
  // =========================
  // STAR WARS
  // =========================
  {
    name: "Ahsoka Tano",
    category: "star-wars",
    kills: 40,
    height: 179,
    age: 45,
    strength: 91,
    intelligence: 88,
    fame: 92,
    attractiveness: 88,
  },
  {
    name: "Anakin Skywalker",
    category: "star-wars",
    kills: 80,
    height: 188,
    age: 22,
    strength: 97,
    intelligence: 86,
    fame: 98,
    attractiveness: 92,
  },
  {
    name: "Boba Fett",
    category: "star-wars",
    kills: 20,
    height: 183,
    age: 41,
    strength: 83,
    intelligence: 84,
    fame: 94,
    attractiveness: 78,
  },
  {
    name: "C-3PO",
    category: "star-wars",
    kills: 0,
    height: 177,
    age: 67,
    strength: 18,
    intelligence: 87,
    fame: 95,
    attractiveness: null,
  },
  {
    name: "Chewbacca",
    category: "star-wars",
    kills: 30,
    height: 228,
    age: 235,
    strength: 88,
    intelligence: 76,
    fame: 97,
    attractiveness: 62,
  },
  {
    name: "Count Dooku",
    category: "star-wars",
    kills: 20,
    height: 193,
    age: 83,
    strength: 93,
    intelligence: 94,
    fame: 85,
    attractiveness: 76,
  },
  {
    name: "Darth Vader",
    category: "star-wars",
    kills: 100,
    height: 203,
    age: 45,
    strength: 98,
    intelligence: 90,
    fame: 100,
    attractiveness: 81,
  },
  {
    name: "Finn",
    category: "star-wars",
    kills: 15,
    height: 178,
    age: 24,
    strength: 69,
    intelligence: 72,
    fame: 83,
    attractiveness: 87,
  },
  {
    name: "General Grievous",
    category: "star-wars",
    kills: 40,
    height: 216,
    age: null,
    strength: 89,
    intelligence: 83,
    fame: 88,
    attractiveness: 30,
  },
  {
    name: "Grogu",
    category: "star-wars",
    kills: 3,
    height: 34,
    age: 50,
    strength: 74,
    intelligence: 60,
    fame: 97,
    attractiveness: null,
  },
  {
    name: "Han Solo",
    category: "star-wars",
    kills: 35,
    height: 180,
    age: 66,
    strength: 73,
    intelligence: 85,
    fame: 98,
    attractiveness: 91,
  },
  {
    name: "Jabba the Hutt",
    category: "star-wars",
    kills: 0,
    height: 175,
    age: 604,
    strength: 52,
    intelligence: 82,
    fame: 89,
    attractiveness: 12,
  },
  {
    name: "Kylo Ren",
    category: "star-wars",
    kills: 20,
    height: 189,
    age: 30,
    strength: 92,
    intelligence: 80,
    fame: 94,
    attractiveness: 91,
  },
  {
    name: "Lando Calrissian",
    category: "star-wars",
    kills: 10,
    height: 177,
    age: 78,
    strength: 65,
    intelligence: 86,
    fame: 87,
    attractiveness: 92,
  },
  {
    name: "Leia Organa",
    category: "star-wars",
    kills: 15,
    height: 155,
    age: 54,
    strength: 72,
    intelligence: 92,
    fame: 98,
    attractiveness: 91,
  },
  {
    name: "Luke Skywalker",
    category: "star-wars",
    kills: 35,
    height: 172,
    age: 53,
    strength: 97,
    intelligence: 88,
    fame: 100,
    attractiveness: 88,
  },
  {
    name: "Mace Windu",
    category: "star-wars",
    kills: 25,
    height: 192,
    age: 53,
    strength: 96,
    intelligence: 90,
    fame: 89,
    attractiveness: 82,
  },
  {
    name: "Mandalorian",
    category: "star-wars",
    kills: 50,
    height: 180,
    age: 40,
    strength: 85,
    intelligence: 80,
    fame: 92,
    attractiveness: 90,
  },
  {
    name: "Obi-Wan Kenobi",
    category: "star-wars",
    kills: 35,
    height: 181,
    age: 56,
    strength: 94,
    intelligence: 92,
    fame: 98,
    attractiveness: 91,
  },
  {
    name: "Padmé Amidala",
    category: "star-wars",
    kills: 10,
    height: 165,
    age: 27,
    strength: 61,
    intelligence: 91,
    fame: 90,
    attractiveness: 94,
  },
  {
    name: "Palpatine",
    category: "star-wars",
    kills: 15,
    height: 173,
    age: 119,
    strength: 99,
    intelligence: 100,
    fame: 98,
    attractiveness: 35,
  },
  {
    name: "Qui-Gon Jinn",
    category: "star-wars",
    kills: 10,
    height: 193,
    age: 48,
    strength: 91,
    intelligence: 91,
    fame: 88,
    attractiveness: 90,
  },
  {
    name: "R2-D2",
    category: "star-wars",
    kills: 2,
    height: 108,
    age: 67,
    strength: 30,
    intelligence: 93,
    fame: 97,
    attractiveness: null,
  },
  {
    name: "Rey",
    category: "star-wars",
    kills: 10,
    height: 170,
    age: 20,
    strength: 93,
    intelligence: 82,
    fame: 93,
    attractiveness: 91,
  },
  {
    name: "Yoda",
    category: "star-wars",
    kills: 10,
    height: 66,
    age: 900,
    strength: 99,
    intelligence: 98,
    fame: 100,
    attractiveness: 35,
  },
    {
    name: "Darth Maul",
    category: "star-wars",
    kills: 35,
    height: 175,
    age: 44,
    strength: 95,
    intelligence: 88,
    fame: 97,
    attractiveness: 90,
  },
  {
    name: "Jango Fett",
    category: "star-wars",
    kills: 30,
    height: 183,
    age: 44,
    strength: 86,
    intelligence: 87,
    fame: 93,
    attractiveness: 88,
  },
  {
    name: "Cad Bane",
    category: "star-wars",
    kills: 40,
    height: 185,
    age: 71,
    strength: 81,
    intelligence: 93,
    fame: 89,
    attractiveness: 74,
  },
  {
    name: "Bo-Katan Kryze",
    category: "star-wars",
    kills: 35,
    height: 170,
    age: 50,
    strength: 84,
    intelligence: 88,
    fame: 90,
    attractiveness: 92,
  },
  {
    name: "Poe Dameron",
    category: "star-wars",
    kills: 20,
    height: 172,
    age: 32,
    strength: 67,
    intelligence: 86,
    fame: 90,
    attractiveness: 92,
  },
  {
    name: "Captain Phasma",
    category: "star-wars",
    kills: 20,
    height: 200,
    age: 40,
    strength: 88,
    intelligence: 82,
    fame: 86,
    attractiveness: 80,
  },
  {
    name: "Grand Moff Tarkin",
    category: "star-wars",
    kills: 5,
    height: 183,
    age: 64,
    strength: 45,
    intelligence: 97,
    fame: 92,
    attractiveness: 72,
  },
  {
    name: "Admiral Ackbar",
    category: "star-wars",
    kills: 5,
    height: 180,
    age: 60,
    strength: 52,
    intelligence: 94,
    fame: 92,
    attractiveness: null,
  },
  {
    name: "Asajj Ventress",
    category: "star-wars",
    kills: 45,
    height: 180,
    age: 30,
    strength: 93,
    intelligence: 89,
    fame: 89,
    attractiveness: 91,
  },
  {
    name: "Kit Fisto",
    category: "star-wars",
    kills: 20,
    height: 196,
    age: 45,
    strength: 91,
    intelligence: 88,
    fame: 85,
    attractiveness: 78,
  },
    {
    name: "Captain Rex",
    category: "star-wars",
    kills: 55,
    height: 183,
    age: 32,
    strength: 86,
    intelligence: 91,
    fame: 92,
    attractiveness: 88,
  },
  {
    name: "Commander Cody",
    category: "star-wars",
    kills: 45,
    height: 183,
    age: 32,
    strength: 85,
    intelligence: 89,
    fame: 88,
    attractiveness: 86,
  },
  {
    name: "Grand Admiral Thrawn",
    category: "star-wars",
    kills: 15,
    height: 188,
    age: 55,
    strength: 74,
    intelligence: 100,
    fame: 93,
    attractiveness: 89,
  },
  {
    name: "Moff Gideon",
    category: "star-wars",
    kills: 25,
    height: 173,
    age: 55,
    strength: 79,
    intelligence: 94,
    fame: 90,
    attractiveness: 82,
  },
  {
    name: "Fennec Shand",
    category: "star-wars",
    kills: 35,
    height: 168,
    age: 55,
    strength: 80,
    intelligence: 91,
    fame: 87,
    attractiveness: 91,
  },
  {
    name: "Kanan Jarrus",
    category: "star-wars",
    kills: 30,
    height: 191,
    age: 32,
    strength: 91,
    intelligence: 89,
    fame: 89,
    attractiveness: 92,
  },
  {
    name: "Ezra Bridger",
    category: "star-wars",
    kills: 20,
    height: 175,
    age: 19,
    strength: 88,
    intelligence: 86,
    fame: 90,
    attractiveness: 89,
  },
  {
    name: "Sabine Wren",
    category: "star-wars",
    kills: 30,
    height: 170,
    age: 30,
    strength: 82,
    intelligence: 91,
    fame: 89,
    attractiveness: 94,
  },
  {
    name: "Hera Syndulla",
    category: "star-wars",
    kills: 15,
    height: 176,
    age: 40,
    strength: 70,
    intelligence: 96,
    fame: 88,
    attractiveness: 92,
  },
  {
    name: "Plo Koon",
    category: "star-wars",
    kills: 25,
    height: 188,
    age: 385,
    strength: 94,
    intelligence: 93,
    fame: 87,
    attractiveness: 73,
  },
  {
    name: "Aayla Secura",
    category: "star-wars",
    kills: 25,
    height: 178,
    age: 30,
    strength: 91,
    intelligence: 88,
    fame: 88,
    attractiveness: 95,
  },
  {
    name: "Savage Opress",
    category: "star-wars",
    kills: 40,
    height: 208,
    age: 35,
    strength: 98,
    intelligence: 72,
    fame: 87,
    attractiveness: 65,
  },
  {
    name: "Pre Vizsla",
    category: "star-wars",
    kills: 30,
    height: 183,
    age: 45,
    strength: 88,
    intelligence: 89,
    fame: 85,
    attractiveness: 88,
  },
  {
    name: "Nute Gunray",
    category: "star-wars",
    kills: 0,
    height: 191,
    age: 65,
    strength: 35,
    intelligence: 85,
    fame: 86,
    attractiveness: 38,
  },
  {
    name: "Wedge Antilles",
    category: "star-wars",
    kills: 20,
    height: 170,
    age: 50,
    strength: 64,
    intelligence: 91,
    fame: 86,
    attractiveness: 87,
  },

  // =========================
  // MARVEL
  // =========================
  {
    name: "Ant-Man",
    category: "marvel",
    kills: 15,
    height: 183,
    age: 50,
    strength: 86,
    intelligence: 85,
    fame: 88,
    attractiveness: 86,
  },
  {
    name: "Black Panther",
    category: "marvel",
    kills: 30,
    height: 183,
    age: 38,
    strength: 88,
    intelligence: 91,
    fame: 95,
    attractiveness: 94,
  },
  {
    name: "Black Widow",
    category: "marvel",
    kills: 45,
    height: 160,
    age: 35,
    strength: 69,
    intelligence: 90,
    fame: 97,
    attractiveness: 96,
  },
  {
    name: "Captain America",
    category: "marvel",
    kills: 60,
    height: 188,
    age: 106,
    strength: 84,
    intelligence: 88,
    fame: 100,
    attractiveness: 95,
  },
  {
    name: "Captain Marvel",
    category: "marvel",
    kills: 45,
    height: 170,
    age: 60,
    strength: 99,
    intelligence: 84,
    fame: 92,
    attractiveness: 91,
  },
  {
    name: "Daredevil",
    category: "marvel",
    kills: 5,
    height: 178,
    age: 35,
    strength: 72,
    intelligence: 88,
    fame: 87,
    attractiveness: 91,
  },
  {
    name: "Deadpool",
    category: "marvel",
    kills: 100,
    height: 188,
    age: 45,
    strength: 83,
    intelligence: 76,
    fame: 97,
    attractiveness: 83,
  },
  {
    name: "Doctor Strange",
    category: "marvel",
    kills: 25,
    height: 183,
    age: 45,
    strength: 98,
    intelligence: 98,
    fame: 95,
    attractiveness: 90,
  },
  {
    name: "Drax",
    category: "marvel",
    kills: 80,
    height: 193,
    age: 50,
    strength: 88,
    intelligence: 58,
    fame: 89,
    attractiveness: 78,
  },
  {
    name: "Gamora",
    category: "marvel",
    kills: 75,
    height: 170,
    age: 30,
    strength: 87,
    intelligence: 86,
    fame: 91,
    attractiveness: 93,
  },
  {
    name: "Groot",
    category: "marvel",
    kills: 25,
    height: 230,
    age: null,
    strength: 90,
    intelligence: 62,
    fame: 96,
    attractiveness: null,
  },
  {
    name: "Hawkeye",
    category: "marvel",
    kills: 50,
    height: 175,
    age: 52,
    strength: 68,
    intelligence: 87,
    fame: 94,
    attractiveness: 86,
  },
  {
    name: "Hulk",
    category: "marvel",
    kills: 80,
    height: 250,
    age: 55,
    strength: 100,
    intelligence: 96,
    fame: 100,
    attractiveness: 65,
  },
  {
    name: "Iron Man",
    category: "marvel",
    kills: 70,
    height: 185,
    age: 53,
    strength: 95,
    intelligence: 100,
    fame: 100,
    attractiveness: 95,
  },
  {
    name: "Loki",
    category: "marvel",
    kills: 40,
    height: 188,
    age: 1050,
    strength: 94,
    intelligence: 96,
    fame: 100,
    attractiveness: 96,
  },
  {
    name: "Moon Knight",
    category: "marvel",
    kills: 20,
    height: 188,
    age: 40,
    strength: 80,
    intelligence: 81,
    fame: 82,
    attractiveness: 88,
  },
  {
    name: "Rocket",
    category: "marvel",
    kills: 40,
    height: 122,
    age: 15,
    strength: 75,
    intelligence: 94,
    fame: 92,
    attractiveness: null,
  },
  {
    name: "Scarlet Witch",
    category: "marvel",
    kills: 45,
    height: 168,
    age: 30,
    strength: 100,
    intelligence: 88,
    fame: 97,
    attractiveness: 92,
  },
  {
    name: "Spider-Man",
    category: "marvel",
    kills: 30,
    height: 173,
    age: 18,
    strength: 91,
    intelligence: 96,
    fame: 100,
    attractiveness: 91,
  },
  {
    name: "Star-Lord",
    category: "marvel",
    kills: 45,
    height: 188,
    age: 43,
    strength: 76,
    intelligence: 82,
    fame: 93,
    attractiveness: 91,
  },
  {
    name: "Thanos",
    category: "marvel",
    kills: 100,
    height: 250,
    age: 1000,
    strength: 100,
    intelligence: 95,
    fame: 100,
    attractiveness: 67,
  },
  {
    name: "Thor",
    category: "marvel",
    kills: 150,
    height: 198,
    age: 1500,
    strength: 100,
    intelligence: 82,
    fame: 100,
    attractiveness: 98,
  },
  {
    name: "Venom",
    category: "marvel",
    kills: 35,
    height: 230,
    age: null,
    strength: 94,
    intelligence: 72,
    fame: 96,
    attractiveness: 72,
  },
  {
    name: "Vision",
    category: "marvel",
    kills: 20,
    height: 190,
    age: 3,
    strength: 97,
    intelligence: 100,
    fame: 94,
    attractiveness: 83,
  },
  {
    name: "Wolverine",
    category: "marvel",
    kills: 150,
    height: 188,
    age: 200,
    strength: 90,
    intelligence: 79,
    fame: 100,
    attractiveness: 94,
  },
    {
    name: "Winter Soldier",
    category: "marvel",
    kills: 60,
    height: 183,
    age: 106,
    strength: 78,
    intelligence: 86,
    fame: 94,
    attractiveness: 94,
  },
  {
    name: "Falcon",
    category: "marvel",
    kills: 30,
    height: 183,
    age: 42,
    strength: 73,
    intelligence: 87,
    fame: 93,
    attractiveness: 92,
  },
  {
    name: "War Machine",
    category: "marvel",
    kills: 50,
    height: 185,
    age: 50,
    strength: 90,
    intelligence: 89,
    fame: 92,
    attractiveness: 88,
  },
  {
    name: "Nick Fury",
    category: "marvel",
    kills: 25,
    height: 183,
    age: 70,
    strength: 63,
    intelligence: 97,
    fame: 96,
    attractiveness: 84,
  },
  {
    name: "Mysterio",
    category: "marvel",
    kills: 10,
    height: 183,
    age: 40,
    strength: 79,
    intelligence: 94,
    fame: 91,
    attractiveness: 90,
  },
  {
    name: "Green Goblin",
    category: "marvel",
    kills: 35,
    height: 180,
    age: 55,
    strength: 86,
    intelligence: 98,
    fame: 97,
    attractiveness: 72,
  },
  {
    name: "Doctor Octopus",
    category: "marvel",
    kills: 20,
    height: 175,
    age: 55,
    strength: 84,
    intelligence: 99,
    fame: 95,
    attractiveness: 75,
  },
  {
    name: "Magneto",
    category: "marvel",
    kills: 100,
    height: 188,
    age: 90,
    strength: 99,
    intelligence: 96,
    fame: 100,
    attractiveness: 90,
  },
  {
    name: "Professor X",
    category: "marvel",
    kills: 5,
    height: 183,
    age: 70,
    strength: 96,
    intelligence: 100,
    fame: 98,
    attractiveness: 82,
  },
  {
    name: "Silver Surfer",
    category: "marvel",
    kills: 30,
    height: 193,
    age: 1000,
    strength: 100,
    intelligence: 95,
    fame: 96,
    attractiveness: 93,
  },
    {
    name: "Punisher",
    category: "marvel",
    kills: 150,
    height: 185,
    age: 45,
    strength: 68,
    intelligence: 88,
    fame: 94,
    attractiveness: 90,
  },
  {
    name: "Blade",
    category: "marvel",
    kills: 120,
    height: 188,
    age: 55,
    strength: 82,
    intelligence: 86,
    fame: 93,
    attractiveness: 91,
  },
  {
    name: "Ghost Rider",
    category: "marvel",
    kills: 180,
    height: 188,
    age: 40,
    strength: 99,
    intelligence: 82,
    fame: 97,
    attractiveness: 84,
  },
  {
    name: "Shang-Chi",
    category: "marvel",
    kills: 25,
    height: 178,
    age: 30,
    strength: 84,
    intelligence: 87,
    fame: 91,
    attractiveness: 95,
  },
  {
    name: "Wasp",
    category: "marvel",
    kills: 15,
    height: 163,
    age: 35,
    strength: 82,
    intelligence: 92,
    fame: 88,
    attractiveness: 94,
  },
  {
    name: "Nebula",
    category: "marvel",
    kills: 70,
    height: 183,
    age: 35,
    strength: 82,
    intelligence: 86,
    fame: 91,
    attractiveness: 86,
  },
  {
    name: "Ultron",
    category: "marvel",
    kills: 500,
    height: 205,
    age: 1,
    strength: 99,
    intelligence: 100,
    fame: 97,
    attractiveness: null,
  },
  {
    name: "Red Skull",
    category: "marvel",
    kills: 80,
    height: 188,
    age: 100,
    strength: 74,
    intelligence: 94,
    fame: 93,
    attractiveness: 45,
  },
  {
    name: "Hela",
    category: "marvel",
    kills: 200,
    height: 175,
    age: 3000,
    strength: 100,
    intelligence: 92,
    fame: 96,
    attractiveness: 96,
  },
  {
    name: "Kingpin",
    category: "marvel",
    kills: 35,
    height: 201,
    age: 50,
    strength: 71,
    intelligence: 97,
    fame: 92,
    attractiveness: 72,
  },
  {
    name: "Cyclops",
    category: "marvel",
    kills: 30,
    height: 190,
    age: 35,
    strength: 92,
    intelligence: 90,
    fame: 94,
    attractiveness: 94,
  },
  {
    name: "Storm",
    category: "marvel",
    kills: 40,
    height: 180,
    age: 35,
    strength: 97,
    intelligence: 91,
    fame: 97,
    attractiveness: 98,
  },
  {
    name: "Jean Grey",
    category: "marvel",
    kills: 60,
    height: 168,
    age: 35,
    strength: 100,
    intelligence: 96,
    fame: 97,
    attractiveness: 98,
  },
  {
    name: "Beast",
    category: "marvel",
    kills: 20,
    height: 191,
    age: 40,
    strength: 80,
    intelligence: 100,
    fame: 91,
    attractiveness: 74,
  },
  {
    name: "Adam Warlock",
    category: "marvel",
    kills: 30,
    height: 188,
    age: 1,
    strength: 99,
    intelligence: 90,
    fame: 90,
    attractiveness: 94,
  },

  // =========================
  // HARRY POTTER
  // =========================
  {
    name: "Albus Dumbledore",
    category: "harry-potter",
    kills: 3,
    height: 185,
    age: 115,
    strength: 100,
    intelligence: 100,
    fame: 98,
    attractiveness: 72,
  },
  {
    name: "Arthur Weasley",
    category: "harry-potter",
    kills: 1,
    height: 188,
    age: 48,
    strength: 76,
    intelligence: 84,
    fame: 77,
    attractiveness: 73,
  },
  {
    name: "Bellatrix Lestrange",
    category: "harry-potter",
    kills: 8,
    height: 170,
    age: 47,
    strength: 94,
    intelligence: 84,
    fame: 92,
    attractiveness: 89,
  },
  {
    name: "Cedric Diggory",
    category: "harry-potter",
    kills: 0,
    height: 185,
    age: 17,
    strength: 79,
    intelligence: 82,
    fame: 86,
    attractiveness: null,
  },
  {
    name: "Dobby",
    category: "harry-potter",
    kills: 0,
    height: 106,
    age: null,
    strength: 82,
    intelligence: 79,
    fame: 94,
    attractiveness: null,
  },
  {
    name: "Dolores Umbridge",
    category: "harry-potter",
    kills: 0,
    height: 160,
    age: 50,
    strength: 68,
    intelligence: 82,
    fame: 90,
    attractiveness: 35,
  },
  {
    name: "Draco Malfoy",
    category: "harry-potter",
    kills: 0,
    height: 183,
    age: 17,
    strength: 76,
    intelligence: 83,
    fame: 95,
    attractiveness: null,
  },
  {
    name: "Fred Weasley",
    category: "harry-potter",
    kills: 2,
    height: 180,
    age: 20,
    strength: 78,
    intelligence: 84,
    fame: 88,
    attractiveness: 86,
  },
  {
    name: "George Weasley",
    category: "harry-potter",
    kills: 2,
    height: 180,
    age: 20,
    strength: 78,
    intelligence: 84,
    fame: 87,
    attractiveness: 86,
  },
  {
    name: "Ginny Weasley",
    category: "harry-potter",
    kills: 2,
    height: 168,
    age: 16,
    strength: 82,
    intelligence: 84,
    fame: 91,
    attractiveness: null,
  },
  {
    name: "Harry Potter",
    category: "harry-potter",
    kills: 5,
    height: 175,
    age: 17,
    strength: 90,
    intelligence: 88,
    fame: 100,
    attractiveness: null,
  },
  {
    name: "Hermine Granger",
    category: "harry-potter",
    kills: 2,
    height: 165,
    age: 18,
    strength: 86,
    intelligence: 97,
    fame: 98,
    attractiveness: 92,
  },
  {
    name: "Lord Voldemort",
    category: "harry-potter",
    kills: 25,
    height: 183,
    age: 71,
    strength: 100,
    intelligence: 97,
    fame: 100,
    attractiveness: 20,
  },
  {
    name: "Lucius Malfoy",
    category: "harry-potter",
    kills: 3,
    height: 183,
    age: 44,
    strength: 84,
    intelligence: 86,
    fame: 88,
    attractiveness: 86,
  },
  {
    name: "Luna Lovegood",
    category: "harry-potter",
    kills: 1,
    height: 163,
    age: 17,
    strength: 75,
    intelligence: 89,
    fame: 91,
    attractiveness: null,
  },
  {
    name: "Minerva McGonagall",
    category: "harry-potter",
    kills: 2,
    height: 175,
    age: 70,
    strength: 95,
    intelligence: 95,
    fame: 94,
    attractiveness: 75,
  },
  {
    name: "Molly Weasley",
    category: "harry-potter",
    kills: 2,
    height: 160,
    age: 48,
    strength: 88,
    intelligence: 84,
    fame: 91,
    attractiveness: 76,
  },
  {
    name: "Neville Longbottom",
    category: "harry-potter",
    kills: 4,
    height: 180,
    age: 17,
    strength: 82,
    intelligence: 82,
    fame: 91,
    attractiveness: null,
  },
  {
    name: "Peter Pettigrew",
    category: "harry-potter",
    kills: 13,
    height: 168,
    age: 38,
    strength: 73,
    intelligence: 78,
    fame: 87,
    attractiveness: 38,
  },
  {
    name: "Remus Lupin",
    category: "harry-potter",
    kills: 4,
    height: 188,
    age: 38,
    strength: 87,
    intelligence: 93,
    fame: 91,
    attractiveness: 87,
  },
  {
    name: "Ron Weasley",
    category: "harry-potter",
    kills: 4,
    height: 185,
    age: 18,
    strength: 71,
    intelligence: 80,
    fame: 98,
    attractiveness: 88,
  },
  {
    name: "Rubeus Hagrid",
    category: "harry-potter",
    kills: 2,
    height: 351,
    age: 69,
    strength: 83,
    intelligence: 72,
    fame: 98,
    attractiveness: 65,
  },
  {
    name: "Severus Snape",
    category: "harry-potter",
    kills: 3,
    height: 183,
    age: 38,
    strength: 96,
    intelligence: 97,
    fame: 98,
    attractiveness: 84,
  },
  {
    name: "Sirius Black",
    category: "harry-potter",
    kills: 3,
    height: 180,
    age: 36,
    strength: 89,
    intelligence: 88,
    fame: 95,
    attractiveness: 94,
  },
  {
    name: "Viktor Krum",
    category: "harry-potter",
    kills: 1,
    height: 183,
    age: 21,
    strength: 77,
    intelligence: 78,
    fame: 80,
    attractiveness: 90,
  },
  {
  name: "Alastor Moody",
  category: "harry-potter",
  kills: 12,
  height: 185,
  age: 60,
  strength: 93,
  intelligence: 94,
  fame: 90,
  attractiveness: 68,
},
{
  name: "Nymphadora Tonks",
  category: "harry-potter",
  kills: 6,
  height: 168,
  age: 25,
  strength: 86,
  intelligence: 86,
  fame: 87,
  attractiveness: 94,
},
{
  name: "Kingsley Shacklebolt",
  category: "harry-potter",
  kills: 7,
  height: 188,
  age: 45,
  strength: 92,
  intelligence: 95,
  fame: 89,
  attractiveness: 90,
},
{
  name: "Horace Slughorn",
  category: "harry-potter",
  kills: 1,
  height: 175,
  age: 70,
  strength: 83,
  intelligence: 96,
  fame: 84,
  attractiveness: 64,
},
{
  name: "Gilderoy Lockhart",
  category: "harry-potter",
  kills: 0,
  height: 183,
  age: 35,
  strength: 58,
  intelligence: 72,
  fame: 93,
  attractiveness: 95,
},
{
  name: "Fleur Delacour",
  category: "harry-potter",
  kills: 1,
  height: 170,
  age: 17,
  strength: 81,
  intelligence: 86,
  fame: 86,
  attractiveness: null,
},
{
  name: "Cho Chang",
  category: "harry-potter",
  kills: 0,
  height: 165,
  age: 17,
  strength: 73,
  intelligence: 84,
  fame: 82,
  attractiveness: null,
},
{
  name: "Narcissa Malfoy",
  category: "harry-potter",
  kills: 0,
  height: 170,
  age: 45,
  strength: 72,
  intelligence: 91,
  fame: 86,
  attractiveness: 94,
},
{
  name: "Barty Crouch Jr.",
  category: "harry-potter",
  kills: 3,
  height: 178,
  age: 33,
  strength: 91,
  intelligence: 96,
  fame: 89,
  attractiveness: 82,
},
{
  name: "Fenrir Greyback",
  category: "harry-potter",
  kills: 15,
  height: 188,
  age: 45,
  strength: 94,
  intelligence: 72,
  fame: 88,
  attractiveness: 48,
},

  // =========================
  // DC
  // =========================
  {
    name: "Aquaman",
    category: "dc",
    kills: 25,
    height: 185,
    age: 40,
    strength: 96,
    intelligence: 84,
    fame: 94,
    attractiveness: 95,
  },
  {
    name: "Bane",
    category: "dc",
    kills: 15,
    height: 203,
    age: 40,
    strength: 92,
    intelligence: 90,
    fame: 91,
    attractiveness: 72,
  },
  {
    name: "Batgirl",
    category: "dc",
    kills: 2,
    height: 170,
    age: 25,
    strength: 72,
    intelligence: 92,
    fame: 88,
    attractiveness: 92,
  },
  {
    name: "Batman",
    category: "dc",
    kills: 10,
    height: 188,
    age: 40,
    strength: 86,
    intelligence: 100,
    fame: 100,
    attractiveness: 96,
  },
  {
    name: "Black Canary",
    category: "dc",
    kills: 5,
    height: 170,
    age: 30,
    strength: 75,
    intelligence: 85,
    fame: 86,
    attractiveness: 94,
  },
  {
    name: "Catwoman",
    category: "dc",
    kills: 5,
    height: 170,
    age: 35,
    strength: 71,
    intelligence: 88,
    fame: 96,
    attractiveness: 97,
  },
  {
    name: "Cyborg",
    category: "dc",
    kills: 20,
    height: 198,
    age: 25,
    strength: 94,
    intelligence: 94,
    fame: 91,
    attractiveness: 82,
  },
  {
    name: "Darkseid",
    category: "dc",
    kills: 100,
    height: 267,
    age: null,
    strength: 100,
    intelligence: 97,
    fame: 95,
    attractiveness: 25,
  },
  {
    name: "Deathstroke",
    category: "dc",
    kills: 100,
    height: 193,
    age: 50,
    strength: 89,
    intelligence: 94,
    fame: 89,
    attractiveness: 84,
  },
  {
    name: "Green Arrow",
    category: "dc",
    kills: 15,
    height: 185,
    age: 40,
    strength: 77,
    intelligence: 88,
    fame: 91,
    attractiveness: 93,
  },
  {
    name: "Green Lantern",
    category: "dc",
    kills: 20,
    height: 188,
    age: 35,
    strength: 72,
    intelligence: 87,
    fame: 94,
    attractiveness: 91,
  },
  {
    name: "Harley Quinn",
    category: "dc",
    kills: 30,
    height: 170,
    age: 30,
    strength: 69,
    intelligence: 82,
    fame: 98,
    attractiveness: 96,
  },
  {
    name: "Joker",
    category: "dc",
    kills: 100,
    height: 196,
    age: 40,
    strength: 62,
    intelligence: 96,
    fame: 100,
    attractiveness: 72,
  },
  {
    name: "Lex Luthor",
    category: "dc",
    kills: 15,
    height: 188,
    age: 45,
    strength: 65,
    intelligence: 100,
    fame: 96,
    attractiveness: 83,
  },
  {
    name: "Mr. Freeze",
    category: "dc",
    kills: 10,
    height: 183,
    age: 50,
    strength: 78,
    intelligence: 97,
    fame: 83,
    attractiveness: 70,
  },
  {
    name: "Nightwing",
    category: "dc",
    kills: 5,
    height: 178,
    age: 27,
    strength: 81,
    intelligence: 90,
    fame: 90,
    attractiveness: 97,
  },
  {
    name: "Penguin",
    category: "dc",
    kills: 20,
    height: 157,
    age: 50,
    strength: 43,
    intelligence: 87,
    fame: 92,
    attractiveness: 45,
  },
  {
    name: "Poison Ivy",
    category: "dc",
    kills: 25,
    height: 173,
    age: 30,
    strength: 84,
    intelligence: 93,
    fame: 91,
    attractiveness: 96,
  },
  {
    name: "Robin",
    category: "dc",
    kills: 2,
    height: 165,
    age: 16,
    strength: 68,
    intelligence: 88,
    fame: 96,
    attractiveness: null,
  },
  {
    name: "Shazam",
    category: "dc",
    kills: 5,
    height: 190,
    age: 15,
    strength: 99,
    intelligence: 72,
    fame: 91,
    attractiveness: null,
  },
  {
    name: "Supergirl",
    category: "dc",
    kills: 15,
    height: 165,
    age: 21,
    strength: 99,
    intelligence: 86,
    fame: 95,
    attractiveness: 94,
  },
  {
    name: "Superman",
    category: "dc",
    kills: 20,
    height: 191,
    age: 35,
    strength: 100,
    intelligence: 92,
    fame: 100,
    attractiveness: 98,
  },
  {
    name: "The Flash",
    category: "dc",
    kills: 10,
    height: 183,
    age: 30,
    strength: 98,
    intelligence: 94,
    fame: 97,
    attractiveness: 93,
  },
  {
    name: "The Riddler",
    category: "dc",
    kills: 5,
    height: 185,
    age: 40,
    strength: 50,
    intelligence: 98,
    fame: 91,
    attractiveness: 73,
  },
  {
    name: "Wonder Woman",
    category: "dc",
    kills: 50,
    height: 183,
    age: 800,
    strength: 99,
    intelligence: 92,
    fame: 100,
    attractiveness: 98,
  },
  {
  name: "Martian Manhunter",
  category: "dc",
  kills: 35,
  height: 201,
  age: 300,
  strength: 100,
  intelligence: 98,
  fame: 93,
  attractiveness: 88,
},
{
  name: "John Constantine",
  category: "dc",
  kills: 12,
  height: 183,
  age: 40,
  strength: 87,
  intelligence: 99,
  fame: 94,
  attractiveness: 91,
},
{
  name: "Raven",
  category: "dc",
  kills: 15,
  height: 165,
  age: 20,
  strength: 99,
  intelligence: 94,
  fame: 96,
  attractiveness: 95,
},
{
  name: "Starfire",
  category: "dc",
  kills: 25,
  height: 193,
  age: 25,
  strength: 97,
  intelligence: 85,
  fame: 94,
  attractiveness: 98,
},
{
  name: "Beast Boy",
  category: "dc",
  kills: 5,
  height: 173,
  age: 20,
  strength: 91,
  intelligence: 82,
  fame: 92,
  attractiveness: 88,
},
{
  name: "Blue Beetle",
  category: "dc",
  kills: 8,
  height: 173,
  age: 18,
  strength: 95,
  intelligence: 87,
  fame: 91,
  attractiveness: 92,
},
{
  name: "Black Adam",
  category: "dc",
  kills: 150,
  height: 191,
  age: 5000,
  strength: 100,
  intelligence: 91,
  fame: 97,
  attractiveness: 92,
},
{
  name: "Lucifer Morningstar",
  category: "dc",
  kills: 50,
  height: 191,
  age: 1000000,
  strength: 100,
  intelligence: 100,
  fame: 98,
  attractiveness: 99,
},
{
  name: "Scarecrow",
  category: "dc",
  kills: 10,
  height: 183,
  age: 45,
  strength: 75,
  intelligence: 97,
  fame: 94,
  attractiveness: 63,
},
{
  name: "Two-Face",
  category: "dc",
  kills: 25,
  height: 183,
  age: 45,
  strength: 72,
  intelligence: 92,
  fame: 96,
  attractiveness: 70,
},

  // =========================
  // FLUCH DER KARIBIK
  // =========================
  {
    name: "Angelica",
    category: "fluch-der-karibik",
    kills: 8,
    height: 168,
    age: 35,
    strength: 71,
    intelligence: 88,
    fame: 83,
    attractiveness: 95,
  },
  {
    name: "Barbossa",
    category: "fluch-der-karibik",
    kills: 35,
    height: 182,
    age: 58,
    strength: 78,
    intelligence: 94,
    fame: 96,
    attractiveness: 72,
  },
  {
    name: "Blackbeard",
    category: "fluch-der-karibik",
    kills: 50,
    height: 188,
    age: 60,
    strength: 88,
    intelligence: 90,
    fame: 88,
    attractiveness: 65,
  },
  {
    name: "Bootstrap Bill",
    category: "fluch-der-karibik",
    kills: 12,
    height: 180,
    age: 50,
    strength: 79,
    intelligence: 75,
    fame: 77,
    attractiveness: 68,
  },
  {
    name: "Captain Teague",
    category: "fluch-der-karibik",
    kills: 30,
    height: 174,
    age: 65,
    strength: 82,
    intelligence: 93,
    fame: 79,
    attractiveness: 72,
  },
  {
    name: "Cotton",
    category: "fluch-der-karibik",
    kills: 8,
    height: 175,
    age: 50,
    strength: 68,
    intelligence: 72,
    fame: 65,
    attractiveness: 60,
  },
  {
    name: "Cutler Beckett",
    category: "fluch-der-karibik",
    kills: 2,
    height: 170,
    age: 40,
    strength: 40,
    intelligence: 96,
    fame: 89,
    attractiveness: 70,
  },
  {
    name: "Davy Jones",
    category: "fluch-der-karibik",
    kills: 60,
    height: 188,
    age: 110,
    strength: 97,
    intelligence: 91,
    fame: 96,
    attractiveness: 35,
  },
  {
    name: "Elizabeth Swann",
    category: "fluch-der-karibik",
    kills: 10,
    height: 170,
    age: 25,
    strength: 69,
    intelligence: 91,
    fame: 97,
    attractiveness: 97,
  },
  {
    name: "Giselle",
    category: "fluch-der-karibik",
    kills: 1,
    height: 168,
    age: 30,
    strength: 50,
    intelligence: 72,
    fame: 62,
    attractiveness: 90,
  },
  {
    name: "Ian Mercer",
    category: "fluch-der-karibik",
    kills: 15,
    height: 180,
    age: 40,
    strength: 75,
    intelligence: 88,
    fame: 63,
    attractiveness: 69,
  },
  {
    name: "Jack Sparrow",
    category: "fluch-der-karibik",
    kills: 25,
    height: 178,
    age: 40,
    strength: 70,
    intelligence: 96,
    fame: 100,
    attractiveness: 94,
  },
  {
    name: "James Norrington",
    category: "fluch-der-karibik",
    kills: 20,
    height: 185,
    age: 35,
    strength: 82,
    intelligence: 90,
    fame: 90,
    attractiveness: 92,
  },
  {
    name: "Joshamee Gibbs",
    category: "fluch-der-karibik",
    kills: 12,
    height: 178,
    age: 50,
    strength: 72,
    intelligence: 84,
    fame: 91,
    attractiveness: 70,
  },
  {
    name: "Lieutenant Theodore Groves",
    category: "fluch-der-karibik",
    kills: 8,
    height: 183,
    age: 35,
    strength: 73,
    intelligence: 82,
    fame: 61,
    attractiveness: 78,
  },
  {
    name: "Marty",
    category: "fluch-der-karibik",
    kills: 5,
    height: 117,
    age: 35,
    strength: 55,
    intelligence: 73,
    fame: 66,
    attractiveness: 67,
  },
  {
    name: "Philip Swift",
    category: "fluch-der-karibik",
    kills: 3,
    height: 183,
    age: 30,
    strength: 72,
    intelligence: 82,
    fame: 68,
    attractiveness: 93,
  },
  {
    name: "Pintel",
    category: "fluch-der-karibik",
    kills: 15,
    height: 178,
    age: 40,
    strength: 74,
    intelligence: 70,
    fame: 81,
    attractiveness: 55,
  },
  {
    name: "Ragetti",
    category: "fluch-der-karibik",
    kills: 12,
    height: 188,
    age: 35,
    strength: 69,
    intelligence: 67,
    fame: 82,
    attractiveness: 58,
  },
  {
    name: "Scrum",
    category: "fluch-der-karibik",
    kills: 8,
    height: 180,
    age: 40,
    strength: 72,
    intelligence: 66,
    fame: 70,
    attractiveness: 62,
  },
  {
    name: "Syrena",
    category: "fluch-der-karibik",
    kills: 3,
    height: 170,
    age: null,
    strength: 82,
    intelligence: 79,
    fame: 75,
    attractiveness: 96,
  },
  {
    name: "Tamara",
    category: "fluch-der-karibik",
    kills: 5,
    height: 168,
    age: null,
    strength: 80,
    intelligence: 75,
    fame: 58,
    attractiveness: 94,
  },
  {
    name: "Tia Dalma",
    category: "fluch-der-karibik",
    kills: 2,
    height: 168,
    age: null,
    strength: 96,
    intelligence: 98,
    fame: 90,
    attractiveness: 87,
  },
  {
    name: "Weatherby Swann",
    category: "fluch-der-karibik",
    kills: 0,
    height: 180,
    age: 55,
    strength: 38,
    intelligence: 86,
    fame: 78,
    attractiveness: 68,
  },
  {
    name: "Will Turner",
    category: "fluch-der-karibik",
    kills: 30,
    height: 180,
    age: 30,
    strength: 84,
    intelligence: 87,
    fame: 98,
    attractiveness: 97,
  },
  {
  name: "Armando Salazar",
  category: "fluch-der-karibik",
  kills: 120,
  height: 188,
  age: 50,
  strength: 96,
  intelligence: 91,
  fame: 94,
  attractiveness: 72,
},
{
  name: "Henry Turner",
  category: "fluch-der-karibik",
  kills: 8,
  height: 180,
  age: 21,
  strength: 78,
  intelligence: 84,
  fame: 88,
  attractiveness: 93,
},
{
  name: "Carina Smyth",
  category: "fluch-der-karibik",
  kills: 1,
  height: 168,
  age: 21,
  strength: 66,
  intelligence: 97,
  fame: 87,
  attractiveness: 95,
},
{
  name: "Sao Feng",
  category: "fluch-der-karibik",
  kills: 35,
  height: 175,
  age: 45,
  strength: 84,
  intelligence: 90,
  fame: 91,
  attractiveness: 80,
},
{
  name: "Maccus",
  category: "fluch-der-karibik",
  kills: 30,
  height: 190,
  age: 45,
  strength: 91,
  intelligence: 74,
  fame: 84,
  attractiveness: 45,
},
{
  name: "Mullroy",
  category: "fluch-der-karibik",
  kills: 4,
  height: 178,
  age: 35,
  strength: 71,
  intelligence: 76,
  fame: 78,
  attractiveness: 72,
},
{
  name: "Murtogg",
  category: "fluch-der-karibik",
  kills: 4,
  height: 180,
  age: 35,
  strength: 72,
  intelligence: 75,
  fame: 78,
  attractiveness: 73,
},
{
  name: "Lieutenant Gillette",
  category: "fluch-der-karibik",
  kills: 6,
  height: 183,
  age: 35,
  strength: 76,
  intelligence: 84,
  fame: 79,
  attractiveness: 82,
},
{
  name: "Scarlett",
  category: "fluch-der-karibik",
  kills: 0,
  height: 165,
  age: 30,
  strength: 58,
  intelligence: 78,
  fame: 79,
  attractiveness: 90,
},
{
  name: "Jack the Monkey",
  category: "fluch-der-karibik",
  kills: 2,
  height: 45,
  age: 10,
  strength: 52,
  intelligence: 70,
  fame: 88,
  attractiveness: null,
},

  // =========================
  // GAME OF THRONES
  // =========================
  {
    name: "Arya Stark",
    category: "game-of-thrones",
    kills: 25,
    height: 155,
    age: 18,
    strength: 66,
    intelligence: 91,
    fame: 98,
    attractiveness: 88,
  },
  {
    name: "Bran Stark",
    category: "game-of-thrones",
    kills: 0,
    height: 180,
    age: 17,
    strength: 35,
    intelligence: 96,
    fame: 91,
    attractiveness: null,
  },
  {
    name: "Brienne von Tarth",
    category: "game-of-thrones",
    kills: 20,
    height: 191,
    age: 32,
    strength: 94,
    intelligence: 83,
    fame: 89,
    attractiveness: 83,
  },
  {
    name: "Catelyn Stark",
    category: "game-of-thrones",
    kills: 1,
    height: 165,
    age: 45,
    strength: 54,
    intelligence: 89,
    fame: 88,
    attractiveness: 85,
  },
  {
    name: "Cersei Lannister",
    category: "game-of-thrones",
    kills: 5,
    height: 166,
    age: 43,
    strength: 52,
    intelligence: 91,
    fame: 97,
    attractiveness: 94,
  },
  {
    name: "Daenerys Targaryen",
    category: "game-of-thrones",
    kills: 120,
    height: 157,
    age: 24,
    strength: 57,
    intelligence: 88,
    fame: 100,
    attractiveness: 97,
  },
  {
    name: "Davos Seaworth",
    category: "game-of-thrones",
    kills: 8,
    height: 185,
    age: 50,
    strength: 69,
    intelligence: 90,
    fame: 87,
    attractiveness: 77,
  },
  {
    name: "Gendry",
    category: "game-of-thrones",
    kills: 10,
    height: 182,
    age: 23,
    strength: 91,
    intelligence: 74,
    fame: 84,
    attractiveness: 93,
  },
  {
    name: "Gregor Clegane",
    category: "game-of-thrones",
    kills: 50,
    height: 206,
    age: 40,
    strength: 100,
    intelligence: 52,
    fame: 92,
    attractiveness: 45,
  },
  {
    name: "Jaime Lannister",
    category: "game-of-thrones",
    kills: 35,
    height: 188,
    age: 43,
    strength: 91,
    intelligence: 88,
    fame: 98,
    attractiveness: 97,
  },
  {
    name: "Jon Snow",
    category: "game-of-thrones",
    kills: 55,
    height: 173,
    age: 24,
    strength: 89,
    intelligence: 84,
    fame: 100,
    attractiveness: 97,
  },
  {
    name: "Jorah Mormont",
    category: "game-of-thrones",
    kills: 40,
    height: 185,
    age: 48,
    strength: 88,
    intelligence: 86,
    fame: 91,
    attractiveness: 87,
  },
  {
    name: "Margaery Tyrell",
    category: "game-of-thrones",
    kills: 0,
    height: 168,
    age: 22,
    strength: 47,
    intelligence: 94,
    fame: 91,
    attractiveness: 97,
  },
  {
    name: "Melisandre",
    category: "game-of-thrones",
    kills: 10,
    height: 168,
    age: 400,
    strength: 54,
    intelligence: 93,
    fame: 92,
    attractiveness: 95,
  },
  {
    name: "Ned Stark",
    category: "game-of-thrones",
    kills: 20,
    height: 179,
    age: 40,
    strength: 84,
    intelligence: 90,
    fame: 97,
    attractiveness: 90,
  },
  {
    name: "Olenna Tyrell",
    category: "game-of-thrones",
    kills: 1,
    height: 174,
    age: 80,
    strength: 35,
    intelligence: 98,
    fame: 89,
    attractiveness: 72,
  },
  {
    name: "Petyr Baelish",
    category: "game-of-thrones",
    kills: 2,
    height: 175,
    age: 40,
    strength: 48,
    intelligence: 99,
    fame: 93,
    attractiveness: 81,
  },
  {
    name: "Robb Stark",
    category: "game-of-thrones",
    kills: 25,
    height: 177,
    age: 20,
    strength: 87,
    intelligence: 87,
    fame: 92,
    attractiveness: 95,
  },
  {
    name: "Samwell Tarly",
    category: "game-of-thrones",
    kills: 5,
    height: 173,
    age: 23,
    strength: 48,
    intelligence: 95,
    fame: 89,
    attractiveness: 77,
  },
  {
    name: "Sandor Clegane",
    category: "game-of-thrones",
    kills: 45,
    height: 198,
    age: 40,
    strength: 96,
    intelligence: 78,
    fame: 96,
    attractiveness: 78,
  },
  {
    name: "Sansa Stark",
    category: "game-of-thrones",
    kills: 1,
    height: 175,
    age: 20,
    strength: 49,
    intelligence: 92,
    fame: 96,
    attractiveness: 97,
  },
  {
    name: "Theon Greyjoy",
    category: "game-of-thrones",
    kills: 20,
    height: 175,
    age: 25,
    strength: 77,
    intelligence: 77,
    fame: 91,
    attractiveness: 86,
  },
  {
    name: "Tormund",
    category: "game-of-thrones",
    kills: 35,
    height: 183,
    age: 40,
    strength: 93,
    intelligence: 71,
    fame: 91,
    attractiveness: 84,
  },
  {
    name: "Tyrion Lannister",
    category: "game-of-thrones",
    kills: 8,
    height: 135,
    age: 40,
    strength: 38,
    intelligence: 100,
    fame: 100,
    attractiveness: 83,
  },
  {
    name: "Varys",
    category: "game-of-thrones",
    kills: 1,
    height: 175,
    age: 50,
    strength: 42,
    intelligence: 99,
    fame: 93,
    attractiveness: 75,
    },

  // =========================
  // HERR DER RINGE
  // =========================
  {
    name: "Frodo Baggins",
    category: "herr-der-ringe",
    kills: 3,
    height: 106,
    age: 50,
    strength: 43,
    intelligence: 87,
    fame: 100,
    attractiveness: 82,
  },
  {
    name: "Samwise Gamgee",
    category: "herr-der-ringe",
    kills: 8,
    height: 107,
    age: 38,
    strength: 67,
    intelligence: 84,
    fame: 98,
    attractiveness: 82,
  },
  {
    name: "Gandalf",
    category: "herr-der-ringe",
    kills: 25,
    height: 180,
    age: 2000,
    strength: 98,
    intelligence: 99,
    fame: 100,
    attractiveness: 76,
  },
  {
    name: "Aragorn",
    category: "herr-der-ringe",
    kills: 70,
    height: 198,
    age: 87,
    strength: 94,
    intelligence: 91,
    fame: 100,
    attractiveness: 98,
  },
  {
    name: "Legolas",
    category: "herr-der-ringe",
    kills: 80,
    height: 183,
    age: 2931,
    strength: 90,
    intelligence: 87,
    fame: 99,
    attractiveness: 98,
  },
  {
    name: "Gimli",
    category: "herr-der-ringe",
    kills: 65,
    height: 145,
    age: 139,
    strength: 95,
    intelligence: 82,
    fame: 98,
    attractiveness: 77,
  },
  {
    name: "Boromir",
    category: "herr-der-ringe",
    kills: 25,
    height: 193,
    age: 41,
    strength: 91,
    intelligence: 83,
    fame: 96,
    attractiveness: 93,
  },
  {
    name: "Merry",
    category: "herr-der-ringe",
    kills: 6,
    height: 108,
    age: 36,
    strength: 58,
    intelligence: 82,
    fame: 89,
    attractiveness: 80,
  },
  {
    name: "Pippin",
    category: "herr-der-ringe",
    kills: 5,
    height: 107,
    age: 28,
    strength: 56,
    intelligence: 77,
    fame: 90,
    attractiveness: 81,
  },
  {
    name: "Gollum",
    category: "herr-der-ringe",
    kills: 5,
    height: 110,
    age: 589,
    strength: 54,
    intelligence: 81,
    fame: 99,
    attractiveness: 18,
  },
  {
    name: "Sauron",
    category: "herr-der-ringe",
    kills: 500,
    height: 274,
    age: 50000,
    strength: 100,
    intelligence: 98,
    fame: 100,
    attractiveness: 45,
  },
  {
    name: "Saruman",
    category: "herr-der-ringe",
    kills: 30,
    height: 188,
    age: 2000,
    strength: 97,
    intelligence: 98,
    fame: 97,
    attractiveness: 73,
  },
  {
    name: "Galadriel",
    category: "herr-der-ringe",
    kills: 10,
    height: 193,
    age: 8000,
    strength: 96,
    intelligence: 99,
    fame: 98,
    attractiveness: 100,
  },
  {
    name: "Elrond",
    category: "herr-der-ringe",
    kills: 25,
    height: 188,
    age: 6500,
    strength: 92,
    intelligence: 98,
    fame: 96,
    attractiveness: 94,
  },
  {
    name: "Arwen",
    category: "herr-der-ringe",
    kills: 2,
    height: 173,
    age: 2778,
    strength: 76,
    intelligence: 91,
    fame: 96,
    attractiveness: 99,
  },
  {
    name: "Éowyn",
    category: "herr-der-ringe",
    kills: 7,
    height: 173,
    age: 24,
    strength: 84,
    intelligence: 84,
    fame: 96,
    attractiveness: 95,
  },
  {
    name: "Théoden",
    category: "herr-der-ringe",
    kills: 15,
    height: 180,
    age: 71,
    strength: 83,
    intelligence: 88,
    fame: 94,
    attractiveness: 77,
  },
  {
    name: "Faramir",
    category: "herr-der-ringe",
    kills: 30,
    height: 188,
    age: 36,
    strength: 88,
    intelligence: 92,
    fame: 91,
    attractiveness: 94,
  },
  {
    name: "Denethor",
    category: "herr-der-ringe",
    kills: 1,
    height: 180,
    age: 89,
    strength: 52,
    intelligence: 90,
    fame: 88,
    attractiveness: 67,
  },
  {
    name: "Éomer",
    category: "herr-der-ringe",
    kills: 45,
    height: 188,
    age: 28,
    strength: 92,
    intelligence: 84,
    fame: 91,
    attractiveness: 95,
  },
  {
    name: "Treebeard",
    category: "herr-der-ringe",
    kills: 20,
    height: 430,
    age: 10000,
    strength: 100,
    intelligence: 91,
    fame: 92,
    attractiveness: 42,
  },
  {
    name: "Witch-king of Angmar",
    category: "herr-der-ringe",
    kills: 100,
    height: 195,
    age: 4000,
    strength: 98,
    intelligence: 91,
    fame: 97,
    attractiveness: 30,
  },
  {
    name: "Gríma Wormtongue",
    category: "herr-der-ringe",
    kills: 1,
    height: 175,
    age: 40,
    strength: 39,
    intelligence: 88,
    fame: 84,
    attractiveness: 42,
  },
    {
    name: "Haldir",
    category: "herr-der-ringe",
    kills: 20,
    height: 183,
    age: 1000,
    strength: 88,
    intelligence: 89,
    fame: 88,
    attractiveness: 94,
  },
  {
    name: "Bilbo Baggins",
    category: "herr-der-ringe",
    kills: 2,
    height: 107,
    age: 111,
    strength: 46,
    intelligence: 91,
    fame: 98,
    attractiveness: 80,
    },

  // =========================
  // HOBBIT
  // =========================
  {
    name: "Thorin Oakenshield",
    category: "hobbit",
    kills: 45,
    height: 157,
    age: 195,
    strength: 94,
    intelligence: 90,
    fame: 98,
    attractiveness: 93,
  },
  {
    name: "Balin",
    category: "hobbit",
    kills: 20,
    height: 145,
    age: 178,
    strength: 82,
    intelligence: 93,
    fame: 89,
    attractiveness: 79,
  },
  {
    name: "Dwalin",
    category: "hobbit",
    kills: 40,
    height: 150,
    age: 169,
    strength: 96,
    intelligence: 78,
    fame: 88,
    attractiveness: 82,
  },
  {
    name: "Fíli",
    category: "hobbit",
    kills: 25,
    height: 150,
    age: 82,
    strength: 88,
    intelligence: 82,
    fame: 91,
    attractiveness: 94,
  },
  {
    name: "Kíli",
    category: "hobbit",
    kills: 25,
    height: 152,
    age: 77,
    strength: 87,
    intelligence: 82,
    fame: 94,
    attractiveness: 97,
  },
  {
    name: "Bofur",
    category: "hobbit",
    kills: 15,
    height: 145,
    age: 120,
    strength: 81,
    intelligence: 80,
    fame: 86,
    attractiveness: 80,
  },
  {
    name: "Bombur",
    category: "hobbit",
    kills: 12,
    height: 140,
    age: 130,
    strength: 89,
    intelligence: 70,
    fame: 87,
    attractiveness: 65,
  },
  {
    name: "Bifur",
    category: "hobbit",
    kills: 15,
    height: 145,
    age: 130,
    strength: 84,
    intelligence: 73,
    fame: 79,
    attractiveness: 68,
  },
  {
    name: "Óin",
    category: "hobbit",
    kills: 12,
    height: 145,
    age: 167,
    strength: 79,
    intelligence: 85,
    fame: 76,
    attractiveness: 70,
  },
  {
    name: "Glóin",
    category: "hobbit",
    kills: 20,
    height: 145,
    age: 158,
    strength: 87,
    intelligence: 82,
    fame: 86,
    attractiveness: 75,
  },
  {
    name: "Nori",
    category: "hobbit",
    kills: 15,
    height: 143,
    age: 125,
    strength: 81,
    intelligence: 83,
    fame: 77,
    attractiveness: 74,
  },
  {
    name: "Dori",
    category: "hobbit",
    kills: 15,
    height: 145,
    age: 135,
    strength: 86,
    intelligence: 80,
    fame: 76,
    attractiveness: 71,
  },
  {
    name: "Ori",
    category: "hobbit",
    kills: 8,
    height: 140,
    age: 115,
    strength: 69,
    intelligence: 84,
    fame: 77,
    attractiveness: 72,
  },
  {
    name: "Bard",
    category: "hobbit",
    kills: 20,
    height: 183,
    age: 40,
    strength: 84,
    intelligence: 91,
    fame: 94,
    attractiveness: 95,
  },
  {
    name: "Thranduil",
    category: "hobbit",
    kills: 45,
    height: 188,
    age: 3000,
    strength: 95,
    intelligence: 94,
    fame: 95,
    attractiveness: 99,
  },
  {
    name: "Tauriel",
    category: "hobbit",
    kills: 40,
    height: 168,
    age: 600,
    strength: 91,
    intelligence: 88,
    fame: 93,
    attractiveness: 98,
  },
  {
    name: "Azog",
    category: "hobbit",
    kills: 80,
    height: 213,
    age: 150,
    strength: 99,
    intelligence: 80,
    fame: 94,
    attractiveness: 38,
  },
  {
    name: "Bolg",
    category: "hobbit",
    kills: 55,
    height: 220,
    age: 100,
    strength: 98,
    intelligence: 70,
    fame: 86,
    attractiveness: 28,
  },
  {
    name: "Smaug",
    category: "hobbit",
    kills: 1000,
    height: 1800,
    age: 170,
    strength: 100,
    intelligence: 95,
    fame: 100,
    attractiveness: 45,
  },
  {
    name: "Beorn",
    category: "hobbit",
    kills: 35,
    height: 205,
    age: 120,
    strength: 100,
    intelligence: 85,
    fame: 91,
    attractiveness: 84,
  },
  {
    name: "Radagast",
    category: "hobbit",
    kills: 10,
    height: 178,
    age: 2000,
    strength: 90,
    intelligence: 92,
    fame: 90,
    attractiveness: 67,
  },
  {
    name: "Master of Lake-town",
    category: "hobbit",
    kills: 0,
    height: 175,
    age: 50,
    strength: 40,
    intelligence: 82,
    fame: 78,
    attractiveness: 48,
  },
  {
    name: "Alfrid",
    category: "hobbit",
    kills: 0,
    height: 180,
    age: 40,
    strength: 35,
    intelligence: 68,
    fame: 72,
    attractiveness: 35,
  },
  {
    name: "Dáin Ironfoot",
    category: "hobbit",
    kills: 50,
    height: 150,
    age: 252,
    strength: 96,
    intelligence: 87,
    fame: 91,
    attractiveness: 78,
  },
  {
    name: "Necromancer",
    category: "hobbit",
    kills: 300,
    height: 240,
    age: 50000,
    strength: 100,
    intelligence: 98,
    fame: 98,
    attractiveness: 30,
    },

  // =========================
  // THE BOYS
  // =========================
  {
    name: "Homelander",
    category: "the-boys",
    kills: 120,
    height: 181,
    age: 41,
    strength: 100,
    intelligence: 86,
    fame: 100,
    attractiveness: 94,
  },
  {
    name: "Billy Butcher",
    category: "the-boys",
    kills: 35,
    height: 185,
    age: 45,
    strength: 84,
    intelligence: 92,
    fame: 98,
    attractiveness: 91,
  },
  {
    name: "Hughie Campbell",
    category: "the-boys",
    kills: 8,
    height: 185,
    age: 30,
    strength: 63,
    intelligence: 86,
    fame: 94,
    attractiveness: 88,
  },
  {
    name: "Starlight",
    category: "the-boys",
    kills: 10,
    height: 168,
    age: 27,
    strength: 91,
    intelligence: 86,
    fame: 97,
    attractiveness: 96,
  },
  {
    name: "Queen Maeve",
    category: "the-boys",
    kills: 25,
    height: 173,
    age: 38,
    strength: 97,
    intelligence: 84,
    fame: 94,
    attractiveness: 96,
  },
  {
    name: "A-Train",
    category: "the-boys",
    kills: 20,
    height: 183,
    age: 33,
    strength: 89,
    intelligence: 75,
    fame: 95,
    attractiveness: 91,
  },
  {
    name: "The Deep",
    category: "the-boys",
    kills: 8,
    height: 183,
    age: 35,
    strength: 82,
    intelligence: 59,
    fame: 93,
    attractiveness: 92,
  },
  {
    name: "Black Noir",
    category: "the-boys",
    kills: 80,
    height: 180,
    age: 50,
    strength: 94,
    intelligence: 82,
    fame: 92,
    attractiveness: 76,
  },
  {
    name: "Soldier Boy",
    category: "the-boys",
    kills: 100,
    height: 185,
    age: 103,
    strength: 99,
    intelligence: 76,
    fame: 97,
    attractiveness: 96,
  },
  {
    name: "Stormfront",
    category: "the-boys",
    kills: 150,
    height: 170,
    age: 101,
    strength: 98,
    intelligence: 90,
    fame: 94,
    attractiveness: 94,
  },
  {
    name: "Kimiko",
    category: "the-boys",
    kills: 60,
    height: 155,
    age: 30,
    strength: 93,
    intelligence: 78,
    fame: 91,
    attractiveness: 92,
  },
  {
    name: "Frenchie",
    category: "the-boys",
    kills: 30,
    height: 173,
    age: 40,
    strength: 69,
    intelligence: 94,
    fame: 91,
    attractiveness: 91,
  },
  {
    name: "Mother's Milk",
    category: "the-boys",
    kills: 25,
    height: 183,
    age: 43,
    strength: 80,
    intelligence: 92,
    fame: 91,
    attractiveness: 90,
  },
  {
    name: "Victoria Neuman",
    category: "the-boys",
    kills: 35,
    height: 163,
    age: 38,
    strength: 92,
    intelligence: 95,
    fame: 89,
    attractiveness: 94,
  },
  {
    name: "Ashley Barrett",
    category: "the-boys",
    kills: 0,
    height: 168,
    age: 40,
    strength: 35,
    intelligence: 81,
    fame: 84,
    attractiveness: 78,
  },
  {
    name: "Stan Edgar",
    category: "the-boys",
    kills: 0,
    height: 173,
    age: 65,
    strength: 42,
    intelligence: 98,
    fame: 89,
    attractiveness: 82,
  },
  {
    name: "Ryan",
    category: "the-boys",
    kills: 6,
    height: 160,
    age: 12,
    strength: 98,
    intelligence: 73,
    fame: 89,
    attractiveness: null,
  },
  {
    name: "Lamplighter",
    category: "the-boys",
    kills: 20,
    height: 180,
    age: 40,
    strength: 88,
    intelligence: 77,
    fame: 80,
    attractiveness: 82,
  },
  {
    name: "Translucent",
    category: "the-boys",
    kills: 10,
    height: 180,
    age: 40,
    strength: 84,
    intelligence: 78,
    fame: 84,
    attractiveness: 80,
  },
  {
    name: "Mesmer",
    category: "the-boys",
    kills: 0,
    height: 175,
    age: 45,
    strength: 38,
    intelligence: 85,
    fame: 75,
    attractiveness: 70,
  },
  {
    name: "Firecracker",
    category: "the-boys",
    kills: 5,
    height: 168,
    age: 35,
    strength: 74,
    intelligence: 72,
    fame: 88,
    attractiveness: 92,
  },
  {
    name: "Sister Sage",
    category: "the-boys",
    kills: 3,
    height: 168,
    age: 32,
    strength: 55,
    intelligence: 100,
    fame: 87,
    attractiveness: 91,
  },
  {
    name: "Tek Knight",
    category: "the-boys",
    kills: 12,
    height: 185,
    age: 40,
    strength: 77,
    intelligence: 96,
    fame: 82,
    attractiveness: 90,
  },
  {
    name: "Popclaw",
    category: "the-boys",
    kills: 4,
    height: 165,
    age: 30,
    strength: 86,
    intelligence: 69,
    fame: 72,
    attractiveness: 91,
  },
  {
    name: "Love Sausage",
    category: "the-boys",
    kills: 8,
    height: 188,
    age: 45,
    strength: 87,
    intelligence: 67,
    fame: 79,
    attractiveness: 66,
    },

  // =========================
  // THE WALKING DEAD
  // =========================
  {
    name: "Rick Grimes",
    category: "the-walking-dead",
    kills: 160,
    height: 178,
    age: 40,
    strength: 88,
    intelligence: 93,
    fame: 100,
    attractiveness: 94,
  },
  {
    name: "Daryl Dixon",
    category: "the-walking-dead",
    kills: 180,
    height: 178,
    age: 45,
    strength: 91,
    intelligence: 88,
    fame: 100,
    attractiveness: 95,
  },
  {
    name: "Michonne",
    category: "the-walking-dead",
    kills: 140,
    height: 170,
    age: 40,
    strength: 92,
    intelligence: 91,
    fame: 98,
    attractiveness: 94,
  },
  {
    name: "Negan",
    category: "the-walking-dead",
    kills: 120,
    height: 188,
    age: 50,
    strength: 90,
    intelligence: 94,
    fame: 100,
    attractiveness: 94,
  },
  {
    name: "Glenn Rhee",
    category: "the-walking-dead",
    kills: 55,
    height: 175,
    age: 25,
    strength: 78,
    intelligence: 91,
    fame: 98,
    attractiveness: 93,
  },
  {
    name: "Maggie Greene",
    category: "the-walking-dead",
    kills: 95,
    height: 170,
    age: 30,
    strength: 85,
    intelligence: 93,
    fame: 98,
    attractiveness: 96,
  },
  {
    name: "Carol Peletier",
    category: "the-walking-dead",
    kills: 130,
    height: 168,
    age: 50,
    strength: 80,
    intelligence: 96,
    fame: 98,
    attractiveness: 85,
  },
  {
    name: "Carl Grimes",
    category: "the-walking-dead",
    kills: 35,
    height: 170,
    age: 16,
    strength: 68,
    intelligence: 82,
    fame: 96,
    attractiveness: null,
  },
  {
    name: "Shane Walsh",
    category: "the-walking-dead",
    kills: 30,
    height: 183,
    age: 35,
    strength: 90,
    intelligence: 82,
    fame: 95,
    attractiveness: 94,
  },
  {
    name: "Hershel Greene",
    category: "the-walking-dead",
    kills: 15,
    height: 178,
    age: 70,
    strength: 60,
    intelligence: 94,
    fame: 94,
    attractiveness: 74,
  },
  {
    name: "The Governor",
    category: "the-walking-dead",
    kills: 65,
    height: 183,
    age: 45,
    strength: 87,
    intelligence: 92,
    fame: 96,
    attractiveness: 84,
  },
  {
    name: "Abraham Ford",
    category: "the-walking-dead",
    kills: 75,
    height: 188,
    age: 40,
    strength: 95,
    intelligence: 84,
    fame: 94,
    attractiveness: 90,
  },
  {
    name: "Rosita Espinosa",
    category: "the-walking-dead",
    kills: 70,
    height: 168,
    age: 30,
    strength: 84,
    intelligence: 88,
    fame: 95,
    attractiveness: 97,
  },
  {
    name: "Eugene Porter",
    category: "the-walking-dead",
    kills: 25,
    height: 183,
    age: 35,
    strength: 57,
    intelligence: 98,
    fame: 94,
    attractiveness: 72,
  },
  {
    name: "Sasha Williams",
    category: "the-walking-dead",
    kills: 65,
    height: 170,
    age: 30,
    strength: 82,
    intelligence: 87,
    fame: 92,
    attractiveness: 94,
  },
  {
    name: "Tyreese Williams",
    category: "the-walking-dead",
    kills: 45,
    height: 190,
    age: 40,
    strength: 96,
    intelligence: 81,
    fame: 91,
    attractiveness: 87,
  },
  {
    name: "Morgan Jones",
    category: "the-walking-dead",
    kills: 100,
    height: 178,
    age: 50,
    strength: 88,
    intelligence: 92,
    fame: 96,
    attractiveness: 84,
  },
  {
    name: "Gabriel Stokes",
    category: "the-walking-dead",
    kills: 45,
    height: 175,
    age: 45,
    strength: 70,
    intelligence: 89,
    fame: 91,
    attractiveness: 80,
  },
  {
    name: "Aaron",
    category: "the-walking-dead",
    kills: 60,
    height: 180,
    age: 40,
    strength: 83,
    intelligence: 91,
    fame: 90,
    attractiveness: 89,
  },
  {
    name: "Jesus",
    category: "the-walking-dead",
    kills: 60,
    height: 180,
    age: 35,
    strength: 92,
    intelligence: 90,
    fame: 93,
    attractiveness: 95,
  },
  {
    name: "Ezekiel",
    category: "the-walking-dead",
    kills: 55,
    height: 180,
    age: 45,
    strength: 82,
    intelligence: 93,
    fame: 94,
    attractiveness: 91,
  },
  {
    name: "Alpha",
    category: "the-walking-dead",
    kills: 75,
    height: 165,
    age: 45,
    strength: 80,
    intelligence: 94,
    fame: 94,
    attractiveness: 58,
  },
  {
    name: "Beta",
    category: "the-walking-dead",
    kills: 100,
    height: 196,
    age: 45,
    strength: 99,
    intelligence: 77,
    fame: 93,
    attractiveness: 68,
  },
  {
    name: "Merle Dixon",
    category: "the-walking-dead",
    kills: 45,
    height: 185,
    age: 45,
    strength: 89,
    intelligence: 79,
    fame: 91,
    attractiveness: 76,
  },
  {
    name: "Andrea",
    category: "the-walking-dead",
    kills: 30,
    height: 168,
    age: 35,
    strength: 75,
    intelligence: 84,
    fame: 92,
    attractiveness: 92,
    },

  // =========================
  // JURASSIC PARK / WORLD
  // =========================
  {
    name: "Alan Grant",
    category: "jurassic",
    kills: 2,
    height: 183,
    age: 50,
    strength: 76,
    intelligence: 95,
    fame: 100,
    attractiveness: 90,
  },
  {
    name: "Ellie Sattler",
    category: "jurassic",
    kills: 1,
    height: 168,
    age: 45,
    strength: 72,
    intelligence: 96,
    fame: 98,
    attractiveness: 94,
  },
  {
    name: "Ian Malcolm",
    category: "jurassic",
    kills: 0,
    height: 194,
    age: 45,
    strength: 57,
    intelligence: 98,
    fame: 100,
    attractiveness: 94,
  },
  {
    name: "John Hammond",
    category: "jurassic",
    kills: 0,
    height: 178,
    age: 75,
    strength: 38,
    intelligence: 91,
    fame: 98,
    attractiveness: 72,
  },
  {
    name: "Lex Murphy",
    category: "jurassic",
    kills: 0,
    height: 155,
    age: 13,
    strength: 42,
    intelligence: 91,
    fame: 88,
    attractiveness: null,
  },
  {
    name: "Tim Murphy",
    category: "jurassic",
    kills: 0,
    height: 140,
    age: 10,
    strength: 38,
    intelligence: 82,
    fame: 87,
    attractiveness: null,
  },
  {
    name: "Dennis Nedry",
    category: "jurassic",
    kills: 0,
    height: 180,
    age: 40,
    strength: 48,
    intelligence: 93,
    fame: 94,
    attractiveness: 55,
  },
  {
    name: "Robert Muldoon",
    category: "jurassic",
    kills: 4,
    height: 188,
    age: 50,
    strength: 84,
    intelligence: 89,
    fame: 91,
    attractiveness: 82,
  },
  {
    name: "Henry Wu",
    category: "jurassic",
    kills: 0,
    height: 178,
    age: 50,
    strength: 45,
    intelligence: 100,
    fame: 94,
    attractiveness: 84,
  },
  {
    name: "Ray Arnold",
    category: "jurassic",
    kills: 0,
    height: 189,
    age: 45,
    strength: 58,
    intelligence: 94,
    fame: 89,
    attractiveness: 81,
  },
  {
    name: "Donald Gennaro",
    category: "jurassic",
    kills: 0,
    height: 178,
    age: 40,
    strength: 47,
    intelligence: 86,
    fame: 85,
    attractiveness: 74,
  },
  {
    name: "Owen Grady",
    category: "jurassic",
    kills: 10,
    height: 188,
    age: 38,
    strength: 91,
    intelligence: 89,
    fame: 100,
    attractiveness: 98,
  },
  {
    name: "Claire Dearing",
    category: "jurassic",
    kills: 3,
    height: 170,
    age: 35,
    strength: 70,
    intelligence: 94,
    fame: 98,
    attractiveness: 97,
  },
  {
    name: "Maisie Lockwood",
    category: "jurassic",
    kills: 0,
    height: 152,
    age: 14,
    strength: 48,
    intelligence: 84,
    fame: 89,
    attractiveness: null,
  },
  {
    name: "Zach Mitchell",
    category: "jurassic",
    kills: 0,
    height: 180,
    age: 16,
    strength: 61,
    intelligence: 78,
    fame: 85,
    attractiveness: null,
  },
  {
    name: "Gray Mitchell",
    category: "jurassic",
    kills: 0,
    height: 150,
    age: 11,
    strength: 40,
    intelligence: 89,
    fame: 87,
    attractiveness: null,
  },
  {
    name: "Barry Sembène",
    category: "jurassic",
    kills: 5,
    height: 183,
    age: 40,
    strength: 86,
    intelligence: 88,
    fame: 84,
    attractiveness: 91,
  },
  {
    name: "Simon Masrani",
    category: "jurassic",
    kills: 0,
    height: 175,
    age: 45,
    strength: 53,
    intelligence: 91,
    fame: 88,
    attractiveness: 84,
  },
  {
    name: "Vic Hoskins",
    category: "jurassic",
    kills: 2,
    height: 178,
    age: 50,
    strength: 82,
    intelligence: 82,
    fame: 86,
    attractiveness: 73,
  },
  {
    name: "Franklin Webb",
    category: "jurassic",
    kills: 0,
    height: 175,
    age: 30,
    strength: 50,
    intelligence: 91,
    fame: 82,
    attractiveness: 80,
  },
  {
    name: "Zia Rodriguez",
    category: "jurassic",
    kills: 1,
    height: 165,
    age: 30,
    strength: 66,
    intelligence: 94,
    fame: 84,
    attractiveness: 91,
  },
  {
    name: "Eli Mills",
    category: "jurassic",
    kills: 2,
    height: 180,
    age: 40,
    strength: 55,
    intelligence: 92,
    fame: 82,
    attractiveness: 78,
  },
  {
    name: "Benjamin Lockwood",
    category: "jurassic",
    kills: 0,
    height: 178,
    age: 80,
    strength: 30,
    intelligence: 91,
    fame: 81,
    attractiveness: 70,
  },
  {
    name: "Kayla Watts",
    category: "jurassic",
    kills: 3,
    height: 173,
    age: 35,
    strength: 80,
    intelligence: 88,
    fame: 86,
    attractiveness: 94,
  },
  {
    name: "Ramsay Cole",
    category: "jurassic",
    kills: 0,
    height: 183,
    age: 35,
    strength: 67,
    intelligence: 93,
    fame: 80,
    attractiveness: 92,
  },
    // =========================
  // SCHAUSPIELERINNEN
  // =========================

  {
    name: "Margot Robbie",
    category: "schauspielerinnen",
    kills: null,
    height: 168,
    age: 36,
    strength: 72,
    intelligence: 88,
    fame: 99,
    attractiveness: 99,
  },
  {
    name: "Ana de Armas",
    category: "schauspielerinnen",
    kills: null,
    height: 168,
    age: 38,
    strength: 70,
    intelligence: 86,
    fame: 96,
    attractiveness: 99,
  },
  {
    name: "Sydney Sweeney",
    category: "schauspielerinnen",
    kills: null,
    height: 161,
    age: 28,
    strength: 71,
    intelligence: 84,
    fame: 96,
    attractiveness: 98,
  },
  {
    name: "Scarlett Johansson",
    category: "schauspielerinnen",
    kills: null,
    height: 160,
    age: 41,
    strength: 79,
    intelligence: 89,
    fame: 100,
    attractiveness: 98,
  },
  {
    name: "Alexandra Daddario",
    category: "schauspielerinnen",
    kills: null,
    height: 173,
    age: 40,
    strength: 72,
    intelligence: 85,
    fame: 92,
    attractiveness: 99,
  },
  {
    name: "Megan Fox",
    category: "schauspielerinnen",
    kills: null,
    height: 163,
    age: 40,
    strength: 70,
    intelligence: 82,
    fame: 97,
    attractiveness: 98,
  },
  {
    name: "Gal Gadot",
    category: "schauspielerinnen",
    kills: null,
    height: 178,
    age: 41,
    strength: 86,
    intelligence: 87,
    fame: 98,
    attractiveness: 99,
  },
  {
    name: "Zendaya",
    category: "schauspielerinnen",
    kills: null,
    height: 178,
    age: 30,
    strength: 70,
    intelligence: 91,
    fame: 100,
    attractiveness: 98,
  },
  {
    name: "Emma Watson",
    category: "schauspielerinnen",
    kills: null,
    height: 165,
    age: 36,
    strength: 66,
    intelligence: 95,
    fame: 99,
    attractiveness: 97,
  },
  {
    name: "Lily Collins",
    category: "schauspielerinnen",
    kills: null,
    height: 165,
    age: 37,
    strength: 65,
    intelligence: 87,
    fame: 93,
    attractiveness: 97,
  },
  {
    name: "Elizabeth Olsen",
    category: "schauspielerinnen",
    kills: null,
    height: 168,
    age: 37,
    strength: 70,
    intelligence: 89,
    fame: 97,
    attractiveness: 98,
  },
  {
    name: "Jennifer Lawrence",
    category: "schauspielerinnen",
    kills: null,
    height: 175,
    age: 36,
    strength: 77,
    intelligence: 88,
    fame: 99,
    attractiveness: 97,
  },
  {
    name: "Emilia Clarke",
    category: "schauspielerinnen",
    kills: null,
    height: 157,
    age: 39,
    strength: 66,
    intelligence: 88,
    fame: 97,
    attractiveness: 98,
  },
  {
    name: "Natalie Portman",
    category: "schauspielerinnen",
    kills: null,
    height: 160,
    age: 45,
    strength: 68,
    intelligence: 97,
    fame: 99,
    attractiveness: 97,
  },
  {
    name: "Anne Hathaway",
    category: "schauspielerinnen",
    kills: null,
    height: 173,
    age: 43,
    strength: 69,
    intelligence: 91,
    fame: 99,
    attractiveness: 97,
  },
  {
    name: "Blake Lively",
    category: "schauspielerinnen",
    kills: null,
    height: 178,
    age: 39,
    strength: 70,
    intelligence: 87,
    fame: 96,
    attractiveness: 98,
  },
  {
    name: "Dakota Johnson",
    category: "schauspielerinnen",
    kills: null,
    height: 171,
    age: 36,
    strength: 65,
    intelligence: 87,
    fame: 95,
    attractiveness: 97,
  },
  {
    name: "Jessica Alba",
    category: "schauspielerinnen",
    kills: null,
    height: 169,
    age: 45,
    strength: 70,
    intelligence: 91,
    fame: 96,
    attractiveness: 98,
  },
  {
    name: "Monica Bellucci",
    category: "schauspielerinnen",
    kills: null,
    height: 171,
    age: 61,
    strength: 62,
    intelligence: 89,
    fame: 96,
    attractiveness: 99,
  },
  {
    name: "Salma Hayek",
    category: "schauspielerinnen",
    kills: null,
    height: 157,
    age: 59,
    strength: 66,
    intelligence: 91,
    fame: 97,
    attractiveness: 98,
  },
  {
    name: "Florence Pugh",
    category: "schauspielerinnen",
    kills: null,
    height: 162,
    age: 30,
    strength: 76,
    intelligence: 88,
    fame: 96,
    attractiveness: 95,
  },
  {
    name: "Hailee Steinfeld",
    category: "schauspielerinnen",
    kills: null,
    height: 173,
    age: 29,
    strength: 69,
    intelligence: 87,
    fame: 95,
    attractiveness: 97,
  },
  {
    name: "Madelyn Cline",
    category: "schauspielerinnen",
    kills: null,
    height: 168,
    age: 28,
    strength: 67,
    intelligence: 83,
    fame: 91,
    attractiveness: 98,
  },
  {
    name: "Victoria Justice",
    category: "schauspielerinnen",
    kills: null,
    height: 166,
    age: 33,
    strength: 66,
    intelligence: 85,
    fame: 91,
    attractiveness: 98,
  },
  {
    name: "Eiza González",
    category: "schauspielerinnen",
    kills: null,
    height: 173,
    age: 36,
    strength: 73,
    intelligence: 86,
    fame: 94,
    attractiveness: 99,
  },
  {
  name: "Inde Navarrette",
  category: "schauspielerinnen",
  kills: null,
  height: 152,
  age: 25,
  strength: 67,
  intelligence: 86,
  fame: 91,
  attractiveness: 100,
},
    // =========================
  // SCHAUSPIELER
  // =========================

  {
    name: "Henry Cavill",
    category: "schauspieler",
    kills: null,
    height: 185,
    age: 43,
    strength: 90,
    intelligence: 89,
    fame: 99,
    attractiveness: 99,
  },
  {
    name: "Chris Hemsworth",
    category: "schauspieler",
    kills: null,
    height: 190,
    age: 43,
    strength: 94,
    intelligence: 86,
    fame: 99,
    attractiveness: 99,
  },
  {
    name: "Chris Evans",
    category: "schauspieler",
    kills: null,
    height: 183,
    age: 45,
    strength: 87,
    intelligence: 88,
    fame: 99,
    attractiveness: 98,
  },
  {
    name: "Ryan Gosling",
    category: "schauspieler",
    kills: null,
    height: 184,
    age: 45,
    strength: 78,
    intelligence: 91,
    fame: 100,
    attractiveness: 98,
  },
  {
    name: "Brad Pitt",
    category: "schauspieler",
    kills: null,
    height: 180,
    age: 62,
    strength: 75,
    intelligence: 89,
    fame: 100,
    attractiveness: 98,
  },
  {
    name: "Leonardo DiCaprio",
    category: "schauspieler",
    kills: null,
    height: 183,
    age: 51,
    strength: 70,
    intelligence: 94,
    fame: 100,
    attractiveness: 94,
  },
  {
    name: "Zac Efron",
    category: "schauspieler",
    kills: null,
    height: 173,
    age: 38,
    strength: 91,
    intelligence: 84,
    fame: 97,
    attractiveness: 98,
  },
  {
    name: "Michael B. Jordan",
    category: "schauspieler",
    kills: null,
    height: 183,
    age: 39,
    strength: 92,
    intelligence: 88,
    fame: 97,
    attractiveness: 99,
  },
  {
    name: "Theo James",
    category: "schauspieler",
    kills: null,
    height: 183,
    age: 41,
    strength: 86,
    intelligence: 89,
    fame: 94,
    attractiveness: 99,
  },
  {
    name: "Jacob Elordi",
    category: "schauspieler",
    kills: null,
    height: 196,
    age: 29,
    strength: 84,
    intelligence: 84,
    fame: 96,
    attractiveness: 99,
  },
  {
    name: "Tom Hardy",
    category: "schauspieler",
    kills: null,
    height: 175,
    age: 48,
    strength: 89,
    intelligence: 90,
    fame: 98,
    attractiveness: 96,
  },
  {
    name: "Jason Momoa",
    category: "schauspieler",
    kills: null,
    height: 193,
    age: 47,
    strength: 95,
    intelligence: 84,
    fame: 98,
    attractiveness: 99,
  },
  {
    name: "Robert Pattinson",
    category: "schauspieler",
    kills: null,
    height: 185,
    age: 40,
    strength: 78,
    intelligence: 92,
    fame: 99,
    attractiveness: 98,
  },
  {
    name: "Ryan Reynolds",
    category: "schauspieler",
    kills: null,
    height: 188,
    age: 49,
    strength: 84,
    intelligence: 91,
    fame: 100,
    attractiveness: 98,
  },
  {
    name: "Chris Pine",
    category: "schauspieler",
    kills: null,
    height: 184,
    age: 46,
    strength: 80,
    intelligence: 89,
    fame: 96,
    attractiveness: 98,
  },
  {
    name: "Sebastian Stan",
    category: "schauspieler",
    kills: null,
    height: 183,
    age: 44,
    strength: 85,
    intelligence: 87,
    fame: 97,
    attractiveness: 98,
  },
  {
    name: "Andrew Garfield",
    category: "schauspieler",
    kills: null,
    height: 179,
    age: 43,
    strength: 77,
    intelligence: 92,
    fame: 98,
    attractiveness: 98,
  },
  {
    name: "Jake Gyllenhaal",
    category: "schauspieler",
    kills: null,
    height: 182,
    age: 45,
    strength: 86,
    intelligence: 92,
    fame: 98,
    attractiveness: 97,
  },
  {
    name: "Aaron Taylor-Johnson",
    category: "schauspieler",
    kills: null,
    height: 180,
    age: 36,
    strength: 88,
    intelligence: 86,
    fame: 95,
    attractiveness: 99,
  },
  {
    name: "Austin Butler",
    category: "schauspieler",
    kills: null,
    height: 183,
    age: 35,
    strength: 79,
    intelligence: 88,
    fame: 97,
    attractiveness: 99,
  },
  {
    name: "Glen Powell",
    category: "schauspieler",
    kills: null,
    height: 183,
    age: 37,
    strength: 85,
    intelligence: 87,
    fame: 96,
    attractiveness: 98,
  },
  {
    name: "Idris Elba",
    category: "schauspieler",
    kills: null,
    height: 189,
    age: 53,
    strength: 89,
    intelligence: 91,
    fame: 98,
    attractiveness: 98,
  },
  {
    name: "Pedro Pascal",
    category: "schauspieler",
    kills: null,
    height: 180,
    age: 51,
    strength: 75,
    intelligence: 91,
    fame: 99,
    attractiveness: 97,
  },
  {
    name: "Jensen Ackles",
    category: "schauspieler",
    kills: null,
    height: 186,
    age: 48,
    strength: 86,
    intelligence: 87,
    fame: 95,
    attractiveness: 99,
  },
  {
    name: "Charles Melton",
    category: "schauspieler",
    kills: null,
    height: 185,
    age: 35,
    strength: 89,
    intelligence: 85,
    fame: 91,
    attractiveness: 99,
  },
  {
  name: "Tom Welling",
  category: "schauspieler",
  kills: null,
  height: 190,
  age: 49,
  strength: 88,
  intelligence: 86,
  fame: 94,
  attractiveness: 100,
},
{
  name: "Paul Walker",
  category: "schauspieler",
  kills: null,
  height: 188,
  age: 40,
  strength: 84,
  intelligence: 86,
  fame: 98,
  attractiveness: 100,
},
];